// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DocumentFiles         string
	DocumentLinks         string
	DocumentVersions      string
	Documents             string
	Files                 string
	FolderPermissions     string
	Folders               string
	GlobalRoles           string
	PermissionDefinitions string
	PortalMemberships     string
	PortalRoles           string
	Portals               string
	Users                 string
}{
	DocumentFiles:         "document_files",
	DocumentLinks:         "document_links",
	DocumentVersions:      "document_versions",
	Documents:             "documents",
	Files:                 "files",
	FolderPermissions:     "folder_permissions",
	Folders:               "folders",
	GlobalRoles:           "global_roles",
	PermissionDefinitions: "permission_definitions",
	PortalMemberships:     "portal_memberships",
	PortalRoles:           "portal_roles",
	Portals:               "portals",
	Users:                 "users",
}
