// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	DocumentFiles               string
	DocumentLinks               string
	DocumentPermissionOverrides string
	DocumentVersions            string
	Documents                   string
	Files                       string
	FolderPermissionOverrides   string
	Folders                     string
	GlobalRoles                 string
	Permissions                 string
	PortalMemberships           string
	PortalRolePermissions       string
	PortalRoles                 string
	Portals                     string
	Users                       string
}{
	DocumentFiles:               "document_files",
	DocumentLinks:               "document_links",
	DocumentPermissionOverrides: "document_permission_overrides",
	DocumentVersions:            "document_versions",
	Documents:                   "documents",
	Files:                       "files",
	FolderPermissionOverrides:   "folder_permission_overrides",
	Folders:                     "folders",
	GlobalRoles:                 "global_roles",
	Permissions:                 "permissions",
	PortalMemberships:           "portal_memberships",
	PortalRolePermissions:       "portal_role_permissions",
	PortalRoles:                 "portal_roles",
	Portals:                     "portals",
	Users:                       "users",
}
