// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DocumentPermissionOverride is an object representing the database table.
type DocumentPermissionOverride struct {
	ID           int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	DocumentID   int64      `boil:"document_id" json:"document_id" toml:"document_id" yaml:"document_id"`
	PortalRoleID null.Int64 `boil:"portal_role_id" json:"portal_role_id,omitempty" toml:"portal_role_id" yaml:"portal_role_id,omitempty"`
	UserID       null.Int64 `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	PermissionID int64      `boil:"permission_id" json:"permission_id" toml:"permission_id" yaml:"permission_id"`
	Allow        bool       `boil:"allow" json:"allow" toml:"allow" yaml:"allow"`
	CreatedBy    int64      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	CreatedAt    time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *documentPermissionOverrideR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L documentPermissionOverrideL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DocumentPermissionOverrideColumns = struct {
	ID           string
	DocumentID   string
	PortalRoleID string
	UserID       string
	PermissionID string
	Allow        string
	CreatedBy    string
	CreatedAt    string
}{
	ID:           "id",
	DocumentID:   "document_id",
	PortalRoleID: "portal_role_id",
	UserID:       "user_id",
	PermissionID: "permission_id",
	Allow:        "allow",
	CreatedBy:    "created_by",
	CreatedAt:    "created_at",
}

var DocumentPermissionOverrideTableColumns = struct {
	ID           string
	DocumentID   string
	PortalRoleID string
	UserID       string
	PermissionID string
	Allow        string
	CreatedBy    string
	CreatedAt    string
}{
	ID:           "document_permission_overrides.id",
	DocumentID:   "document_permission_overrides.document_id",
	PortalRoleID: "document_permission_overrides.portal_role_id",
	UserID:       "document_permission_overrides.user_id",
	PermissionID: "document_permission_overrides.permission_id",
	Allow:        "document_permission_overrides.allow",
	CreatedBy:    "document_permission_overrides.created_by",
	CreatedAt:    "document_permission_overrides.created_at",
}

// Generated where

type whereHelpernull_Int64 struct{ field string }

func (w whereHelpernull_Int64) EQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, false, x)
}
func (w whereHelpernull_Int64) NEQ(x null.Int64) qm.QueryMod {
	return qmhelper.WhereNullEQ(w.field, true, x)
}
func (w whereHelpernull_Int64) LT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpernull_Int64) LTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpernull_Int64) GT(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpernull_Int64) GTE(x null.Int64) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}
func (w whereHelpernull_Int64) IN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereIn(fmt.Sprintf("%s IN ?", w.field), values...)
}
func (w whereHelpernull_Int64) NIN(slice []int64) qm.QueryMod {
	values := make([]any, 0, len(slice))
	for _, value := range slice {
		values = append(values, value)
	}
	return qm.WhereNotIn(fmt.Sprintf("%s NOT IN ?", w.field), values...)
}

func (w whereHelpernull_Int64) IsNull() qm.QueryMod    { return qmhelper.WhereIsNull(w.field) }
func (w whereHelpernull_Int64) IsNotNull() qm.QueryMod { return qmhelper.WhereIsNotNull(w.field) }

type whereHelperbool struct{ field string }

func (w whereHelperbool) EQ(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.EQ, x) }
func (w whereHelperbool) NEQ(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.NEQ, x) }
func (w whereHelperbool) LT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.LT, x) }
func (w whereHelperbool) LTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.LTE, x) }
func (w whereHelperbool) GT(x bool) qm.QueryMod  { return qmhelper.Where(w.field, qmhelper.GT, x) }
func (w whereHelperbool) GTE(x bool) qm.QueryMod { return qmhelper.Where(w.field, qmhelper.GTE, x) }

var DocumentPermissionOverrideWhere = struct {
	ID           whereHelperint64
	DocumentID   whereHelperint64
	PortalRoleID whereHelpernull_Int64
	UserID       whereHelpernull_Int64
	PermissionID whereHelperint64
	Allow        whereHelperbool
	CreatedBy    whereHelperint64
	CreatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"document_permission_overrides\".\"id\""},
	DocumentID:   whereHelperint64{field: "\"document_permission_overrides\".\"document_id\""},
	PortalRoleID: whereHelpernull_Int64{field: "\"document_permission_overrides\".\"portal_role_id\""},
	UserID:       whereHelpernull_Int64{field: "\"document_permission_overrides\".\"user_id\""},
	PermissionID: whereHelperint64{field: "\"document_permission_overrides\".\"permission_id\""},
	Allow:        whereHelperbool{field: "\"document_permission_overrides\".\"allow\""},
	CreatedBy:    whereHelperint64{field: "\"document_permission_overrides\".\"created_by\""},
	CreatedAt:    whereHelpertime_Time{field: "\"document_permission_overrides\".\"created_at\""},
}

// DocumentPermissionOverrideRels is where relationship names are stored.
var DocumentPermissionOverrideRels = struct {
	CreatedByUser string
	Document      string
	Permission    string
	PortalRole    string
	User          string
}{
	CreatedByUser: "CreatedByUser",
	Document:      "Document",
	Permission:    "Permission",
	PortalRole:    "PortalRole",
	User:          "User",
}

// documentPermissionOverrideR is where relationships are stored.
type documentPermissionOverrideR struct {
	CreatedByUser *User       `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Document      *Document   `boil:"Document" json:"Document" toml:"Document" yaml:"Document"`
	Permission    *Permission `boil:"Permission" json:"Permission" toml:"Permission" yaml:"Permission"`
	PortalRole    *PortalRole `boil:"PortalRole" json:"PortalRole" toml:"PortalRole" yaml:"PortalRole"`
	User          *User       `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*documentPermissionOverrideR) NewStruct() *documentPermissionOverrideR {
	return &documentPermissionOverrideR{}
}

func (o *DocumentPermissionOverride) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *documentPermissionOverrideR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *DocumentPermissionOverride) GetDocument() *Document {
	if o == nil {
		return nil
	}

	return o.R.GetDocument()
}

func (r *documentPermissionOverrideR) GetDocument() *Document {
	if r == nil {
		return nil
	}

	return r.Document
}

func (o *DocumentPermissionOverride) GetPermission() *Permission {
	if o == nil {
		return nil
	}

	return o.R.GetPermission()
}

func (r *documentPermissionOverrideR) GetPermission() *Permission {
	if r == nil {
		return nil
	}

	return r.Permission
}

func (o *DocumentPermissionOverride) GetPortalRole() *PortalRole {
	if o == nil {
		return nil
	}

	return o.R.GetPortalRole()
}

func (r *documentPermissionOverrideR) GetPortalRole() *PortalRole {
	if r == nil {
		return nil
	}

	return r.PortalRole
}

func (o *DocumentPermissionOverride) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *documentPermissionOverrideR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// documentPermissionOverrideL is where Load methods for each relationship are stored.
type documentPermissionOverrideL struct{}

var (
	documentPermissionOverrideAllColumns            = []string{"id", "document_id", "portal_role_id", "user_id", "permission_id", "allow", "created_by", "created_at"}
	documentPermissionOverrideColumnsWithoutDefault = []string{"document_id", "permission_id", "allow", "created_by"}
	documentPermissionOverrideColumnsWithDefault    = []string{"id", "portal_role_id", "user_id", "created_at"}
	documentPermissionOverridePrimaryKeyColumns     = []string{"id"}
	documentPermissionOverrideGeneratedColumns      = []string{"id"}
)

type (
	// DocumentPermissionOverrideSlice is an alias for a slice of pointers to DocumentPermissionOverride.
	// This should almost always be used instead of []DocumentPermissionOverride.
	DocumentPermissionOverrideSlice []*DocumentPermissionOverride

	documentPermissionOverrideQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	documentPermissionOverrideType                 = reflect.TypeOf(&DocumentPermissionOverride{})
	documentPermissionOverrideMapping              = queries.MakeStructMapping(documentPermissionOverrideType)
	documentPermissionOverridePrimaryKeyMapping, _ = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, documentPermissionOverridePrimaryKeyColumns)
	documentPermissionOverrideInsertCacheMut       sync.RWMutex
	documentPermissionOverrideInsertCache          = make(map[string]insertCache)
	documentPermissionOverrideUpdateCacheMut       sync.RWMutex
	documentPermissionOverrideUpdateCache          = make(map[string]updateCache)
	documentPermissionOverrideUpsertCacheMut       sync.RWMutex
	documentPermissionOverrideUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single documentPermissionOverride record from the query.
func (q documentPermissionOverrideQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DocumentPermissionOverride, error) {
	o := &DocumentPermissionOverride{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for document_permission_overrides")
	}

	return o, nil
}

// All returns all DocumentPermissionOverride records from the query.
func (q documentPermissionOverrideQuery) All(ctx context.Context, exec boil.ContextExecutor) (DocumentPermissionOverrideSlice, error) {
	var o []*DocumentPermissionOverride

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DocumentPermissionOverride slice")
	}

	return o, nil
}

// Count returns the count of all DocumentPermissionOverride records in the query.
func (q documentPermissionOverrideQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count document_permission_overrides rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q documentPermissionOverrideQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if document_permission_overrides exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *DocumentPermissionOverride) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Document pointed to by the foreign key.
func (o *DocumentPermissionOverride) Document(mods ...qm.QueryMod) documentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DocumentID),
	}

	queryMods = append(queryMods, mods...)

	return Documents(queryMods...)
}

// Permission pointed to by the foreign key.
func (o *DocumentPermissionOverride) Permission(mods ...qm.QueryMod) permissionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PermissionID),
	}

	queryMods = append(queryMods, mods...)

	return Permissions(queryMods...)
}

// PortalRole pointed to by the foreign key.
func (o *DocumentPermissionOverride) PortalRole(mods ...qm.QueryMod) portalRoleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PortalRoleID),
	}

	queryMods = append(queryMods, mods...)

	return PortalRoles(queryMods...)
}

// User pointed to by the foreign key.
func (o *DocumentPermissionOverride) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentPermissionOverrideL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentPermissionOverride any, mods queries.Applicator) error {
	var slice []*DocumentPermissionOverride
	var object *DocumentPermissionOverride

	if singular {
		var ok bool
		object, ok = maybeDocumentPermissionOverride.(*DocumentPermissionOverride)
		if !ok {
			object = new(DocumentPermissionOverride)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentPermissionOverride))
			}
		}
	} else {
		s, ok := maybeDocumentPermissionOverride.(*[]*DocumentPermissionOverride)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentPermissionOverride))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentPermissionOverrideR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentPermissionOverrideR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByDocumentPermissionOverrides = append(foreign.R.CreatedByDocumentPermissionOverrides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByDocumentPermissionOverrides = append(foreign.R.CreatedByDocumentPermissionOverrides, local)
				break
			}
		}
	}

	return nil
}

// LoadDocument allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentPermissionOverrideL) LoadDocument(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentPermissionOverride any, mods queries.Applicator) error {
	var slice []*DocumentPermissionOverride
	var object *DocumentPermissionOverride

	if singular {
		var ok bool
		object, ok = maybeDocumentPermissionOverride.(*DocumentPermissionOverride)
		if !ok {
			object = new(DocumentPermissionOverride)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentPermissionOverride))
			}
		}
	} else {
		s, ok := maybeDocumentPermissionOverride.(*[]*DocumentPermissionOverride)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentPermissionOverride))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentPermissionOverrideR{}
		}
		args[object.DocumentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentPermissionOverrideR{}
			}

			args[obj.DocumentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`documents`),
		qm.WhereIn(`documents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Document")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Document")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for documents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for documents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Document = foreign
		if foreign.R == nil {
			foreign.R = &documentR{}
		}
		foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DocumentID == foreign.ID {
				local.R.Document = foreign
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, local)
				break
			}
		}
	}

	return nil
}

// LoadPermission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentPermissionOverrideL) LoadPermission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentPermissionOverride any, mods queries.Applicator) error {
	var slice []*DocumentPermissionOverride
	var object *DocumentPermissionOverride

	if singular {
		var ok bool
		object, ok = maybeDocumentPermissionOverride.(*DocumentPermissionOverride)
		if !ok {
			object = new(DocumentPermissionOverride)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentPermissionOverride))
			}
		}
	} else {
		s, ok := maybeDocumentPermissionOverride.(*[]*DocumentPermissionOverride)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentPermissionOverride))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentPermissionOverrideR{}
		}
		args[object.PermissionID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentPermissionOverrideR{}
			}

			args[obj.PermissionID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`permissions`),
		qm.WhereIn(`permissions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Permission")
	}

	var resultSlice []*Permission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Permission")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for permissions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for permissions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Permission = foreign
		if foreign.R == nil {
			foreign.R = &permissionR{}
		}
		foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PermissionID == foreign.ID {
				local.R.Permission = foreign
				if foreign.R == nil {
					foreign.R = &permissionR{}
				}
				foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, local)
				break
			}
		}
	}

	return nil
}

// LoadPortalRole allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentPermissionOverrideL) LoadPortalRole(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentPermissionOverride any, mods queries.Applicator) error {
	var slice []*DocumentPermissionOverride
	var object *DocumentPermissionOverride

	if singular {
		var ok bool
		object, ok = maybeDocumentPermissionOverride.(*DocumentPermissionOverride)
		if !ok {
			object = new(DocumentPermissionOverride)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentPermissionOverride))
			}
		}
	} else {
		s, ok := maybeDocumentPermissionOverride.(*[]*DocumentPermissionOverride)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentPermissionOverride))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentPermissionOverrideR{}
		}
		if !queries.IsNil(object.PortalRoleID) {
			args[object.PortalRoleID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentPermissionOverrideR{}
			}

			if !queries.IsNil(obj.PortalRoleID) {
				args[obj.PortalRoleID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`portal_roles`),
		qm.WhereIn(`portal_roles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PortalRole")
	}

	var resultSlice []*PortalRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PortalRole")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for portal_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for portal_roles")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.PortalRole = foreign
		if foreign.R == nil {
			foreign.R = &portalRoleR{}
		}
		foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.PortalRoleID, foreign.ID) {
				local.R.PortalRole = foreign
				if foreign.R == nil {
					foreign.R = &portalRoleR{}
				}
				foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentPermissionOverrideL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentPermissionOverride any, mods queries.Applicator) error {
	var slice []*DocumentPermissionOverride
	var object *DocumentPermissionOverride

	if singular {
		var ok bool
		object, ok = maybeDocumentPermissionOverride.(*DocumentPermissionOverride)
		if !ok {
			object = new(DocumentPermissionOverride)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentPermissionOverride))
			}
		}
	} else {
		s, ok := maybeDocumentPermissionOverride.(*[]*DocumentPermissionOverride)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentPermissionOverride)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentPermissionOverride))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentPermissionOverrideR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentPermissionOverrideR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.DocumentPermissionOverrides = append(foreign.R.DocumentPermissionOverrides, local)
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the documentPermissionOverride to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByDocumentPermissionOverrides.
func (o *DocumentPermissionOverride) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &documentPermissionOverrideR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByDocumentPermissionOverrides: DocumentPermissionOverrideSlice{o},
		}
	} else {
		related.R.CreatedByDocumentPermissionOverrides = append(related.R.CreatedByDocumentPermissionOverrides, o)
	}

	return nil
}

// SetDocument of the documentPermissionOverride to the related item.
// Sets o.R.Document to related.
// Adds o to related.R.DocumentPermissionOverrides.
func (o *DocumentPermissionOverride) SetDocument(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Document) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"document_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DocumentID = related.ID
	if o.R == nil {
		o.R = &documentPermissionOverrideR{
			Document: related,
		}
	} else {
		o.R.Document = related
	}

	if related.R == nil {
		related.R = &documentR{
			DocumentPermissionOverrides: DocumentPermissionOverrideSlice{o},
		}
	} else {
		related.R.DocumentPermissionOverrides = append(related.R.DocumentPermissionOverrides, o)
	}

	return nil
}

// SetPermission of the documentPermissionOverride to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.DocumentPermissionOverrides.
func (o *DocumentPermissionOverride) SetPermission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Permission) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"permission_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PermissionID = related.ID
	if o.R == nil {
		o.R = &documentPermissionOverrideR{
			Permission: related,
		}
	} else {
		o.R.Permission = related
	}

	if related.R == nil {
		related.R = &permissionR{
			DocumentPermissionOverrides: DocumentPermissionOverrideSlice{o},
		}
	} else {
		related.R.DocumentPermissionOverrides = append(related.R.DocumentPermissionOverrides, o)
	}

	return nil
}

// SetPortalRole of the documentPermissionOverride to the related item.
// Sets o.R.PortalRole to related.
// Adds o to related.R.DocumentPermissionOverrides.
func (o *DocumentPermissionOverride) SetPortalRole(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PortalRole) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"portal_role_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.PortalRoleID, related.ID)
	if o.R == nil {
		o.R = &documentPermissionOverrideR{
			PortalRole: related,
		}
	} else {
		o.R.PortalRole = related
	}

	if related.R == nil {
		related.R = &portalRoleR{
			DocumentPermissionOverrides: DocumentPermissionOverrideSlice{o},
		}
	} else {
		related.R.DocumentPermissionOverrides = append(related.R.DocumentPermissionOverrides, o)
	}

	return nil
}

// RemovePortalRole relationship.
// Sets o.R.PortalRole to nil.
// Removes o from all passed in related items' relationships struct.
func (o *DocumentPermissionOverride) RemovePortalRole(ctx context.Context, exec boil.ContextExecutor, related *PortalRole) error {
	var err error

	queries.SetScanner(&o.PortalRoleID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("portal_role_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.PortalRole = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DocumentPermissionOverrides {
		if queries.Equal(o.PortalRoleID, ri.PortalRoleID) {
			continue
		}

		ln := len(related.R.DocumentPermissionOverrides)
		if ln > 1 && i < ln-1 {
			related.R.DocumentPermissionOverrides[i] = related.R.DocumentPermissionOverrides[ln-1]
		}
		related.R.DocumentPermissionOverrides = related.R.DocumentPermissionOverrides[:ln-1]
		break
	}
	return nil
}

// SetUser of the documentPermissionOverride to the related item.
// Sets o.R.User to related.
// Adds o to related.R.DocumentPermissionOverrides.
func (o *DocumentPermissionOverride) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &documentPermissionOverrideR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			DocumentPermissionOverrides: DocumentPermissionOverrideSlice{o},
		}
	} else {
		related.R.DocumentPermissionOverrides = append(related.R.DocumentPermissionOverrides, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *DocumentPermissionOverride) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.DocumentPermissionOverrides {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.DocumentPermissionOverrides)
		if ln > 1 && i < ln-1 {
			related.R.DocumentPermissionOverrides[i] = related.R.DocumentPermissionOverrides[ln-1]
		}
		related.R.DocumentPermissionOverrides = related.R.DocumentPermissionOverrides[:ln-1]
		break
	}
	return nil
}

// DocumentPermissionOverrides retrieves all the records using an executor.
func DocumentPermissionOverrides(mods ...qm.QueryMod) documentPermissionOverrideQuery {
	mods = append(mods, qm.From("\"document_permission_overrides\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"document_permission_overrides\".*"})
	}

	return documentPermissionOverrideQuery{q}
}

// FindDocumentPermissionOverride retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDocumentPermissionOverride(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DocumentPermissionOverride, error) {
	documentPermissionOverrideObj := &DocumentPermissionOverride{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"document_permission_overrides\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, documentPermissionOverrideObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from document_permission_overrides")
	}

	return documentPermissionOverrideObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DocumentPermissionOverride) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no document_permission_overrides provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentPermissionOverrideColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	documentPermissionOverrideInsertCacheMut.RLock()
	cache, cached := documentPermissionOverrideInsertCache[key]
	documentPermissionOverrideInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			documentPermissionOverrideAllColumns,
			documentPermissionOverrideColumnsWithDefault,
			documentPermissionOverrideColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, documentPermissionOverrideGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"document_permission_overrides\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"document_permission_overrides\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into document_permission_overrides")
	}

	if !cached {
		documentPermissionOverrideInsertCacheMut.Lock()
		documentPermissionOverrideInsertCache[key] = cache
		documentPermissionOverrideInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DocumentPermissionOverride.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DocumentPermissionOverride) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	documentPermissionOverrideUpdateCacheMut.RLock()
	cache, cached := documentPermissionOverrideUpdateCache[key]
	documentPermissionOverrideUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			documentPermissionOverrideAllColumns,
			documentPermissionOverridePrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, documentPermissionOverrideGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update document_permission_overrides, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"document_permission_overrides\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, documentPermissionOverridePrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, append(wl, documentPermissionOverridePrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update document_permission_overrides row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for document_permission_overrides")
	}

	if !cached {
		documentPermissionOverrideUpdateCacheMut.Lock()
		documentPermissionOverrideUpdateCache[key] = cache
		documentPermissionOverrideUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q documentPermissionOverrideQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for document_permission_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for document_permission_overrides")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DocumentPermissionOverrideSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPermissionOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"document_permission_overrides\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, documentPermissionOverridePrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in documentPermissionOverride slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all documentPermissionOverride")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DocumentPermissionOverride) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no document_permission_overrides provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentPermissionOverrideColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	documentPermissionOverrideUpsertCacheMut.RLock()
	cache, cached := documentPermissionOverrideUpsertCache[key]
	documentPermissionOverrideUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			documentPermissionOverrideAllColumns,
			documentPermissionOverrideColumnsWithDefault,
			documentPermissionOverrideColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			documentPermissionOverrideAllColumns,
			documentPermissionOverridePrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, documentPermissionOverrideGeneratedColumns)
		update = strmangle.SetComplement(update, documentPermissionOverrideGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert document_permission_overrides, could not build update column list")
		}

		ret := strmangle.SetComplement(documentPermissionOverrideAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(documentPermissionOverridePrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert document_permission_overrides, could not build conflict column list")
			}

			conflict = make([]string, len(documentPermissionOverridePrimaryKeyColumns))
			copy(conflict, documentPermissionOverridePrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"document_permission_overrides\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(documentPermissionOverrideType, documentPermissionOverrideMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert document_permission_overrides")
	}

	if !cached {
		documentPermissionOverrideUpsertCacheMut.Lock()
		documentPermissionOverrideUpsertCache[key] = cache
		documentPermissionOverrideUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DocumentPermissionOverride record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DocumentPermissionOverride) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DocumentPermissionOverride provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), documentPermissionOverridePrimaryKeyMapping)
	sql := "DELETE FROM \"document_permission_overrides\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from document_permission_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for document_permission_overrides")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q documentPermissionOverrideQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no documentPermissionOverrideQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from document_permission_overrides")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_permission_overrides")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DocumentPermissionOverrideSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPermissionOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"document_permission_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentPermissionOverridePrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from documentPermissionOverride slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_permission_overrides")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DocumentPermissionOverride) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDocumentPermissionOverride(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DocumentPermissionOverrideSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DocumentPermissionOverrideSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPermissionOverridePrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"document_permission_overrides\".* FROM \"document_permission_overrides\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentPermissionOverridePrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DocumentPermissionOverrideSlice")
	}

	*o = slice

	return nil
}

// DocumentPermissionOverrideExists checks if the DocumentPermissionOverride row exists.
func DocumentPermissionOverrideExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"document_permission_overrides\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if document_permission_overrides exists")
	}

	return exists, nil
}

// Exists checks if the DocumentPermissionOverride row exists.
func (o *DocumentPermissionOverride) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DocumentPermissionOverrideExists(ctx, exec, o.ID)
}
