// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DocumentLink is an object representing the database table.
type DocumentLink struct {
	ID               int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	SourceDocumentID int64     `boil:"source_document_id" json:"source_document_id" toml:"source_document_id" yaml:"source_document_id"`
	TargetDocumentID int64     `boil:"target_document_id" json:"target_document_id" toml:"target_document_id" yaml:"target_document_id"`
	CreatedBy        int64     `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	CreatedAt        time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *documentLinkR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L documentLinkL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DocumentLinkColumns = struct {
	ID               string
	SourceDocumentID string
	TargetDocumentID string
	CreatedBy        string
	CreatedAt        string
}{
	ID:               "id",
	SourceDocumentID: "source_document_id",
	TargetDocumentID: "target_document_id",
	CreatedBy:        "created_by",
	CreatedAt:        "created_at",
}

var DocumentLinkTableColumns = struct {
	ID               string
	SourceDocumentID string
	TargetDocumentID string
	CreatedBy        string
	CreatedAt        string
}{
	ID:               "document_links.id",
	SourceDocumentID: "document_links.source_document_id",
	TargetDocumentID: "document_links.target_document_id",
	CreatedBy:        "document_links.created_by",
	CreatedAt:        "document_links.created_at",
}

// Generated where

var DocumentLinkWhere = struct {
	ID               whereHelperint64
	SourceDocumentID whereHelperint64
	TargetDocumentID whereHelperint64
	CreatedBy        whereHelperint64
	CreatedAt        whereHelpertime_Time
}{
	ID:               whereHelperint64{field: "\"document_links\".\"id\""},
	SourceDocumentID: whereHelperint64{field: "\"document_links\".\"source_document_id\""},
	TargetDocumentID: whereHelperint64{field: "\"document_links\".\"target_document_id\""},
	CreatedBy:        whereHelperint64{field: "\"document_links\".\"created_by\""},
	CreatedAt:        whereHelpertime_Time{field: "\"document_links\".\"created_at\""},
}

// DocumentLinkRels is where relationship names are stored.
var DocumentLinkRels = struct {
	CreatedByUser  string
	SourceDocument string
	TargetDocument string
}{
	CreatedByUser:  "CreatedByUser",
	SourceDocument: "SourceDocument",
	TargetDocument: "TargetDocument",
}

// documentLinkR is where relationships are stored.
type documentLinkR struct {
	CreatedByUser  *User     `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	SourceDocument *Document `boil:"SourceDocument" json:"SourceDocument" toml:"SourceDocument" yaml:"SourceDocument"`
	TargetDocument *Document `boil:"TargetDocument" json:"TargetDocument" toml:"TargetDocument" yaml:"TargetDocument"`
}

// NewStruct creates a new relationship struct
func (*documentLinkR) NewStruct() *documentLinkR {
	return &documentLinkR{}
}

func (o *DocumentLink) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *documentLinkR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *DocumentLink) GetSourceDocument() *Document {
	if o == nil {
		return nil
	}

	return o.R.GetSourceDocument()
}

func (r *documentLinkR) GetSourceDocument() *Document {
	if r == nil {
		return nil
	}

	return r.SourceDocument
}

func (o *DocumentLink) GetTargetDocument() *Document {
	if o == nil {
		return nil
	}

	return o.R.GetTargetDocument()
}

func (r *documentLinkR) GetTargetDocument() *Document {
	if r == nil {
		return nil
	}

	return r.TargetDocument
}

// documentLinkL is where Load methods for each relationship are stored.
type documentLinkL struct{}

var (
	documentLinkAllColumns            = []string{"id", "source_document_id", "target_document_id", "created_by", "created_at"}
	documentLinkColumnsWithoutDefault = []string{"source_document_id", "target_document_id", "created_by"}
	documentLinkColumnsWithDefault    = []string{"id", "created_at"}
	documentLinkPrimaryKeyColumns     = []string{"id"}
	documentLinkGeneratedColumns      = []string{"id"}
)

type (
	// DocumentLinkSlice is an alias for a slice of pointers to DocumentLink.
	// This should almost always be used instead of []DocumentLink.
	DocumentLinkSlice []*DocumentLink

	documentLinkQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	documentLinkType                 = reflect.TypeOf(&DocumentLink{})
	documentLinkMapping              = queries.MakeStructMapping(documentLinkType)
	documentLinkPrimaryKeyMapping, _ = queries.BindMapping(documentLinkType, documentLinkMapping, documentLinkPrimaryKeyColumns)
	documentLinkInsertCacheMut       sync.RWMutex
	documentLinkInsertCache          = make(map[string]insertCache)
	documentLinkUpdateCacheMut       sync.RWMutex
	documentLinkUpdateCache          = make(map[string]updateCache)
	documentLinkUpsertCacheMut       sync.RWMutex
	documentLinkUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single documentLink record from the query.
func (q documentLinkQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DocumentLink, error) {
	o := &DocumentLink{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for document_links")
	}

	return o, nil
}

// All returns all DocumentLink records from the query.
func (q documentLinkQuery) All(ctx context.Context, exec boil.ContextExecutor) (DocumentLinkSlice, error) {
	var o []*DocumentLink

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DocumentLink slice")
	}

	return o, nil
}

// Count returns the count of all DocumentLink records in the query.
func (q documentLinkQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count document_links rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q documentLinkQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if document_links exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *DocumentLink) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// SourceDocument pointed to by the foreign key.
func (o *DocumentLink) SourceDocument(mods ...qm.QueryMod) documentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.SourceDocumentID),
	}

	queryMods = append(queryMods, mods...)

	return Documents(queryMods...)
}

// TargetDocument pointed to by the foreign key.
func (o *DocumentLink) TargetDocument(mods ...qm.QueryMod) documentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.TargetDocumentID),
	}

	queryMods = append(queryMods, mods...)

	return Documents(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentLinkL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentLink any, mods queries.Applicator) error {
	var slice []*DocumentLink
	var object *DocumentLink

	if singular {
		var ok bool
		object, ok = maybeDocumentLink.(*DocumentLink)
		if !ok {
			object = new(DocumentLink)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentLink))
			}
		}
	} else {
		s, ok := maybeDocumentLink.(*[]*DocumentLink)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentLink))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentLinkR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentLinkR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByDocumentLinks = append(foreign.R.CreatedByDocumentLinks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByDocumentLinks = append(foreign.R.CreatedByDocumentLinks, local)
				break
			}
		}
	}

	return nil
}

// LoadSourceDocument allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentLinkL) LoadSourceDocument(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentLink any, mods queries.Applicator) error {
	var slice []*DocumentLink
	var object *DocumentLink

	if singular {
		var ok bool
		object, ok = maybeDocumentLink.(*DocumentLink)
		if !ok {
			object = new(DocumentLink)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentLink))
			}
		}
	} else {
		s, ok := maybeDocumentLink.(*[]*DocumentLink)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentLink))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentLinkR{}
		}
		args[object.SourceDocumentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentLinkR{}
			}

			args[obj.SourceDocumentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`documents`),
		qm.WhereIn(`documents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Document")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Document")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for documents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for documents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.SourceDocument = foreign
		if foreign.R == nil {
			foreign.R = &documentR{}
		}
		foreign.R.SourceDocumentDocumentLinks = append(foreign.R.SourceDocumentDocumentLinks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.SourceDocumentID == foreign.ID {
				local.R.SourceDocument = foreign
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.SourceDocumentDocumentLinks = append(foreign.R.SourceDocumentDocumentLinks, local)
				break
			}
		}
	}

	return nil
}

// LoadTargetDocument allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentLinkL) LoadTargetDocument(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentLink any, mods queries.Applicator) error {
	var slice []*DocumentLink
	var object *DocumentLink

	if singular {
		var ok bool
		object, ok = maybeDocumentLink.(*DocumentLink)
		if !ok {
			object = new(DocumentLink)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentLink))
			}
		}
	} else {
		s, ok := maybeDocumentLink.(*[]*DocumentLink)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentLink)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentLink))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentLinkR{}
		}
		args[object.TargetDocumentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentLinkR{}
			}

			args[obj.TargetDocumentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`documents`),
		qm.WhereIn(`documents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Document")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Document")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for documents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for documents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.TargetDocument = foreign
		if foreign.R == nil {
			foreign.R = &documentR{}
		}
		foreign.R.TargetDocumentDocumentLinks = append(foreign.R.TargetDocumentDocumentLinks, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.TargetDocumentID == foreign.ID {
				local.R.TargetDocument = foreign
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.TargetDocumentDocumentLinks = append(foreign.R.TargetDocumentDocumentLinks, local)
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the documentLink to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByDocumentLinks.
func (o *DocumentLink) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_links\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, documentLinkPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &documentLinkR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByDocumentLinks: DocumentLinkSlice{o},
		}
	} else {
		related.R.CreatedByDocumentLinks = append(related.R.CreatedByDocumentLinks, o)
	}

	return nil
}

// SetSourceDocument of the documentLink to the related item.
// Sets o.R.SourceDocument to related.
// Adds o to related.R.SourceDocumentDocumentLinks.
func (o *DocumentLink) SetSourceDocument(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Document) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_links\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"source_document_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentLinkPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.SourceDocumentID = related.ID
	if o.R == nil {
		o.R = &documentLinkR{
			SourceDocument: related,
		}
	} else {
		o.R.SourceDocument = related
	}

	if related.R == nil {
		related.R = &documentR{
			SourceDocumentDocumentLinks: DocumentLinkSlice{o},
		}
	} else {
		related.R.SourceDocumentDocumentLinks = append(related.R.SourceDocumentDocumentLinks, o)
	}

	return nil
}

// SetTargetDocument of the documentLink to the related item.
// Sets o.R.TargetDocument to related.
// Adds o to related.R.TargetDocumentDocumentLinks.
func (o *DocumentLink) SetTargetDocument(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Document) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_links\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"target_document_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentLinkPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.TargetDocumentID = related.ID
	if o.R == nil {
		o.R = &documentLinkR{
			TargetDocument: related,
		}
	} else {
		o.R.TargetDocument = related
	}

	if related.R == nil {
		related.R = &documentR{
			TargetDocumentDocumentLinks: DocumentLinkSlice{o},
		}
	} else {
		related.R.TargetDocumentDocumentLinks = append(related.R.TargetDocumentDocumentLinks, o)
	}

	return nil
}

// DocumentLinks retrieves all the records using an executor.
func DocumentLinks(mods ...qm.QueryMod) documentLinkQuery {
	mods = append(mods, qm.From("\"document_links\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"document_links\".*"})
	}

	return documentLinkQuery{q}
}

// FindDocumentLink retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDocumentLink(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DocumentLink, error) {
	documentLinkObj := &DocumentLink{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"document_links\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, documentLinkObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from document_links")
	}

	return documentLinkObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DocumentLink) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no document_links provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentLinkColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	documentLinkInsertCacheMut.RLock()
	cache, cached := documentLinkInsertCache[key]
	documentLinkInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			documentLinkAllColumns,
			documentLinkColumnsWithDefault,
			documentLinkColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, documentLinkGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(documentLinkType, documentLinkMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(documentLinkType, documentLinkMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"document_links\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"document_links\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into document_links")
	}

	if !cached {
		documentLinkInsertCacheMut.Lock()
		documentLinkInsertCache[key] = cache
		documentLinkInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DocumentLink.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DocumentLink) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	documentLinkUpdateCacheMut.RLock()
	cache, cached := documentLinkUpdateCache[key]
	documentLinkUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			documentLinkAllColumns,
			documentLinkPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, documentLinkGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update document_links, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"document_links\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, documentLinkPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(documentLinkType, documentLinkMapping, append(wl, documentLinkPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update document_links row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for document_links")
	}

	if !cached {
		documentLinkUpdateCacheMut.Lock()
		documentLinkUpdateCache[key] = cache
		documentLinkUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q documentLinkQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for document_links")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for document_links")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DocumentLinkSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"document_links\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, documentLinkPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in documentLink slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all documentLink")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DocumentLink) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no document_links provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentLinkColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	documentLinkUpsertCacheMut.RLock()
	cache, cached := documentLinkUpsertCache[key]
	documentLinkUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			documentLinkAllColumns,
			documentLinkColumnsWithDefault,
			documentLinkColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			documentLinkAllColumns,
			documentLinkPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, documentLinkGeneratedColumns)
		update = strmangle.SetComplement(update, documentLinkGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert document_links, could not build update column list")
		}

		ret := strmangle.SetComplement(documentLinkAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(documentLinkPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert document_links, could not build conflict column list")
			}

			conflict = make([]string, len(documentLinkPrimaryKeyColumns))
			copy(conflict, documentLinkPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"document_links\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(documentLinkType, documentLinkMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(documentLinkType, documentLinkMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert document_links")
	}

	if !cached {
		documentLinkUpsertCacheMut.Lock()
		documentLinkUpsertCache[key] = cache
		documentLinkUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DocumentLink record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DocumentLink) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DocumentLink provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), documentLinkPrimaryKeyMapping)
	sql := "DELETE FROM \"document_links\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from document_links")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for document_links")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q documentLinkQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no documentLinkQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from document_links")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_links")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DocumentLinkSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"document_links\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentLinkPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from documentLink slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_links")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DocumentLink) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDocumentLink(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DocumentLinkSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DocumentLinkSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentLinkPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"document_links\".* FROM \"document_links\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentLinkPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DocumentLinkSlice")
	}

	*o = slice

	return nil
}

// DocumentLinkExists checks if the DocumentLink row exists.
func DocumentLinkExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"document_links\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if document_links exists")
	}

	return exists, nil
}

// Exists checks if the DocumentLink row exists.
func (o *DocumentLink) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DocumentLinkExists(ctx, exec, o.ID)
}
