// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Document is an object representing the database table.
type Document struct {
	ID              int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FolderID        int64      `boil:"folder_id" json:"folder_id" toml:"folder_id" yaml:"folder_id"`
	OwnerID         null.Int64 `boil:"owner_id" json:"owner_id,omitempty" toml:"owner_id" yaml:"owner_id,omitempty"`
	CreatedBy       int64      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	UpdatedBy       null.Int64 `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	Title           string     `boil:"title" json:"title" toml:"title" yaml:"title"`
	LatestVersionID null.Int64 `boil:"latest_version_id" json:"latest_version_id,omitempty" toml:"latest_version_id" yaml:"latest_version_id,omitempty"`
	CreatedAt       time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt       time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *documentR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L documentL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DocumentColumns = struct {
	ID              string
	FolderID        string
	OwnerID         string
	CreatedBy       string
	UpdatedBy       string
	Title           string
	LatestVersionID string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "id",
	FolderID:        "folder_id",
	OwnerID:         "owner_id",
	CreatedBy:       "created_by",
	UpdatedBy:       "updated_by",
	Title:           "title",
	LatestVersionID: "latest_version_id",
	CreatedAt:       "created_at",
	UpdatedAt:       "updated_at",
}

var DocumentTableColumns = struct {
	ID              string
	FolderID        string
	OwnerID         string
	CreatedBy       string
	UpdatedBy       string
	Title           string
	LatestVersionID string
	CreatedAt       string
	UpdatedAt       string
}{
	ID:              "documents.id",
	FolderID:        "documents.folder_id",
	OwnerID:         "documents.owner_id",
	CreatedBy:       "documents.created_by",
	UpdatedBy:       "documents.updated_by",
	Title:           "documents.title",
	LatestVersionID: "documents.latest_version_id",
	CreatedAt:       "documents.created_at",
	UpdatedAt:       "documents.updated_at",
}

// Generated where

var DocumentWhere = struct {
	ID              whereHelperint64
	FolderID        whereHelperint64
	OwnerID         whereHelpernull_Int64
	CreatedBy       whereHelperint64
	UpdatedBy       whereHelpernull_Int64
	Title           whereHelperstring
	LatestVersionID whereHelpernull_Int64
	CreatedAt       whereHelpertime_Time
	UpdatedAt       whereHelpertime_Time
}{
	ID:              whereHelperint64{field: "\"documents\".\"id\""},
	FolderID:        whereHelperint64{field: "\"documents\".\"folder_id\""},
	OwnerID:         whereHelpernull_Int64{field: "\"documents\".\"owner_id\""},
	CreatedBy:       whereHelperint64{field: "\"documents\".\"created_by\""},
	UpdatedBy:       whereHelpernull_Int64{field: "\"documents\".\"updated_by\""},
	Title:           whereHelperstring{field: "\"documents\".\"title\""},
	LatestVersionID: whereHelpernull_Int64{field: "\"documents\".\"latest_version_id\""},
	CreatedAt:       whereHelpertime_Time{field: "\"documents\".\"created_at\""},
	UpdatedAt:       whereHelpertime_Time{field: "\"documents\".\"updated_at\""},
}

// DocumentRels is where relationship names are stored.
var DocumentRels = struct {
	CreatedByUser               string
	Folder                      string
	Owner                       string
	UpdatedByUser               string
	DocumentFiles               string
	SourceDocumentDocumentLinks string
	TargetDocumentDocumentLinks string
	DocumentPermissionOverrides string
	DocumentVersions            string
}{
	CreatedByUser:               "CreatedByUser",
	Folder:                      "Folder",
	Owner:                       "Owner",
	UpdatedByUser:               "UpdatedByUser",
	DocumentFiles:               "DocumentFiles",
	SourceDocumentDocumentLinks: "SourceDocumentDocumentLinks",
	TargetDocumentDocumentLinks: "TargetDocumentDocumentLinks",
	DocumentPermissionOverrides: "DocumentPermissionOverrides",
	DocumentVersions:            "DocumentVersions",
}

// documentR is where relationships are stored.
type documentR struct {
	CreatedByUser               *User                           `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Folder                      *Folder                         `boil:"Folder" json:"Folder" toml:"Folder" yaml:"Folder"`
	Owner                       *User                           `boil:"Owner" json:"Owner" toml:"Owner" yaml:"Owner"`
	UpdatedByUser               *User                           `boil:"UpdatedByUser" json:"UpdatedByUser" toml:"UpdatedByUser" yaml:"UpdatedByUser"`
	DocumentFiles               DocumentFileSlice               `boil:"DocumentFiles" json:"DocumentFiles" toml:"DocumentFiles" yaml:"DocumentFiles"`
	SourceDocumentDocumentLinks DocumentLinkSlice               `boil:"SourceDocumentDocumentLinks" json:"SourceDocumentDocumentLinks" toml:"SourceDocumentDocumentLinks" yaml:"SourceDocumentDocumentLinks"`
	TargetDocumentDocumentLinks DocumentLinkSlice               `boil:"TargetDocumentDocumentLinks" json:"TargetDocumentDocumentLinks" toml:"TargetDocumentDocumentLinks" yaml:"TargetDocumentDocumentLinks"`
	DocumentPermissionOverrides DocumentPermissionOverrideSlice `boil:"DocumentPermissionOverrides" json:"DocumentPermissionOverrides" toml:"DocumentPermissionOverrides" yaml:"DocumentPermissionOverrides"`
	DocumentVersions            DocumentVersionSlice            `boil:"DocumentVersions" json:"DocumentVersions" toml:"DocumentVersions" yaml:"DocumentVersions"`
}

// NewStruct creates a new relationship struct
func (*documentR) NewStruct() *documentR {
	return &documentR{}
}

func (o *Document) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *documentR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *Document) GetFolder() *Folder {
	if o == nil {
		return nil
	}

	return o.R.GetFolder()
}

func (r *documentR) GetFolder() *Folder {
	if r == nil {
		return nil
	}

	return r.Folder
}

func (o *Document) GetOwner() *User {
	if o == nil {
		return nil
	}

	return o.R.GetOwner()
}

func (r *documentR) GetOwner() *User {
	if r == nil {
		return nil
	}

	return r.Owner
}

func (o *Document) GetUpdatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUpdatedByUser()
}

func (r *documentR) GetUpdatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.UpdatedByUser
}

func (o *Document) GetDocumentFiles() DocumentFileSlice {
	if o == nil {
		return nil
	}

	return o.R.GetDocumentFiles()
}

func (r *documentR) GetDocumentFiles() DocumentFileSlice {
	if r == nil {
		return nil
	}

	return r.DocumentFiles
}

func (o *Document) GetSourceDocumentDocumentLinks() DocumentLinkSlice {
	if o == nil {
		return nil
	}

	return o.R.GetSourceDocumentDocumentLinks()
}

func (r *documentR) GetSourceDocumentDocumentLinks() DocumentLinkSlice {
	if r == nil {
		return nil
	}

	return r.SourceDocumentDocumentLinks
}

func (o *Document) GetTargetDocumentDocumentLinks() DocumentLinkSlice {
	if o == nil {
		return nil
	}

	return o.R.GetTargetDocumentDocumentLinks()
}

func (r *documentR) GetTargetDocumentDocumentLinks() DocumentLinkSlice {
	if r == nil {
		return nil
	}

	return r.TargetDocumentDocumentLinks
}

func (o *Document) GetDocumentPermissionOverrides() DocumentPermissionOverrideSlice {
	if o == nil {
		return nil
	}

	return o.R.GetDocumentPermissionOverrides()
}

func (r *documentR) GetDocumentPermissionOverrides() DocumentPermissionOverrideSlice {
	if r == nil {
		return nil
	}

	return r.DocumentPermissionOverrides
}

func (o *Document) GetDocumentVersions() DocumentVersionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetDocumentVersions()
}

func (r *documentR) GetDocumentVersions() DocumentVersionSlice {
	if r == nil {
		return nil
	}

	return r.DocumentVersions
}

// documentL is where Load methods for each relationship are stored.
type documentL struct{}

var (
	documentAllColumns            = []string{"id", "folder_id", "owner_id", "created_by", "updated_by", "title", "latest_version_id", "created_at", "updated_at"}
	documentColumnsWithoutDefault = []string{"folder_id", "created_by", "title"}
	documentColumnsWithDefault    = []string{"id", "owner_id", "updated_by", "latest_version_id", "created_at", "updated_at"}
	documentPrimaryKeyColumns     = []string{"id"}
	documentGeneratedColumns      = []string{"id"}
)

type (
	// DocumentSlice is an alias for a slice of pointers to Document.
	// This should almost always be used instead of []Document.
	DocumentSlice []*Document

	documentQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	documentType                 = reflect.TypeOf(&Document{})
	documentMapping              = queries.MakeStructMapping(documentType)
	documentPrimaryKeyMapping, _ = queries.BindMapping(documentType, documentMapping, documentPrimaryKeyColumns)
	documentInsertCacheMut       sync.RWMutex
	documentInsertCache          = make(map[string]insertCache)
	documentUpdateCacheMut       sync.RWMutex
	documentUpdateCache          = make(map[string]updateCache)
	documentUpsertCacheMut       sync.RWMutex
	documentUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single document record from the query.
func (q documentQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Document, error) {
	o := &Document{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for documents")
	}

	return o, nil
}

// All returns all Document records from the query.
func (q documentQuery) All(ctx context.Context, exec boil.ContextExecutor) (DocumentSlice, error) {
	var o []*Document

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Document slice")
	}

	return o, nil
}

// Count returns the count of all Document records in the query.
func (q documentQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count documents rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q documentQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if documents exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *Document) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Folder pointed to by the foreign key.
func (o *Document) Folder(mods ...qm.QueryMod) folderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FolderID),
	}

	queryMods = append(queryMods, mods...)

	return Folders(queryMods...)
}

// Owner pointed to by the foreign key.
func (o *Document) Owner(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.OwnerID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// UpdatedByUser pointed to by the foreign key.
func (o *Document) UpdatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UpdatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// DocumentFiles retrieves all the document_file's DocumentFiles with an executor.
func (o *Document) DocumentFiles(mods ...qm.QueryMod) documentFileQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"document_files\".\"document_id\"=?", o.ID),
	)

	return DocumentFiles(queryMods...)
}

// SourceDocumentDocumentLinks retrieves all the document_link's DocumentLinks with an executor via source_document_id column.
func (o *Document) SourceDocumentDocumentLinks(mods ...qm.QueryMod) documentLinkQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"document_links\".\"source_document_id\"=?", o.ID),
	)

	return DocumentLinks(queryMods...)
}

// TargetDocumentDocumentLinks retrieves all the document_link's DocumentLinks with an executor via target_document_id column.
func (o *Document) TargetDocumentDocumentLinks(mods ...qm.QueryMod) documentLinkQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"document_links\".\"target_document_id\"=?", o.ID),
	)

	return DocumentLinks(queryMods...)
}

// DocumentPermissionOverrides retrieves all the document_permission_override's DocumentPermissionOverrides with an executor.
func (o *Document) DocumentPermissionOverrides(mods ...qm.QueryMod) documentPermissionOverrideQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"document_permission_overrides\".\"document_id\"=?", o.ID),
	)

	return DocumentPermissionOverrides(queryMods...)
}

// DocumentVersions retrieves all the document_version's DocumentVersions with an executor.
func (o *Document) DocumentVersions(mods ...qm.QueryMod) documentVersionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"document_versions\".\"document_id\"=?", o.ID),
	)

	return DocumentVersions(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByDocuments = append(foreign.R.CreatedByDocuments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByDocuments = append(foreign.R.CreatedByDocuments, local)
				break
			}
		}
	}

	return nil
}

// LoadFolder allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentL) LoadFolder(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.FolderID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}

			args[obj.FolderID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folders`),
		qm.WhereIn(`folders.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Folder")
	}

	var resultSlice []*Folder
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Folder")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for folders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folders")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Folder = foreign
		if foreign.R == nil {
			foreign.R = &folderR{}
		}
		foreign.R.Documents = append(foreign.R.Documents, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FolderID == foreign.ID {
				local.R.Folder = foreign
				if foreign.R == nil {
					foreign.R = &folderR{}
				}
				foreign.R.Documents = append(foreign.R.Documents, local)
				break
			}
		}
	}

	return nil
}

// LoadOwner allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentL) LoadOwner(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		if !queries.IsNil(object.OwnerID) {
			args[object.OwnerID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}

			if !queries.IsNil(obj.OwnerID) {
				args[obj.OwnerID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Owner = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.OwnerDocuments = append(foreign.R.OwnerDocuments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.OwnerID, foreign.ID) {
				local.R.Owner = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.OwnerDocuments = append(foreign.R.OwnerDocuments, local)
				break
			}
		}
	}

	return nil
}

// LoadUpdatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentL) LoadUpdatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		if !queries.IsNil(object.UpdatedBy) {
			args[object.UpdatedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}

			if !queries.IsNil(obj.UpdatedBy) {
				args[obj.UpdatedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UpdatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UpdatedByDocuments = append(foreign.R.UpdatedByDocuments, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UpdatedBy, foreign.ID) {
				local.R.UpdatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UpdatedByDocuments = append(foreign.R.UpdatedByDocuments, local)
				break
			}
		}
	}

	return nil
}

// LoadDocumentFiles allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (documentL) LoadDocumentFiles(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`document_files`),
		qm.WhereIn(`document_files.document_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load document_files")
	}

	var resultSlice []*DocumentFile
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice document_files")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on document_files")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document_files")
	}

	if singular {
		object.R.DocumentFiles = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentFileR{}
			}
			foreign.R.Document = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.DocumentID {
				local.R.DocumentFiles = append(local.R.DocumentFiles, foreign)
				if foreign.R == nil {
					foreign.R = &documentFileR{}
				}
				foreign.R.Document = local
				break
			}
		}
	}

	return nil
}

// LoadSourceDocumentDocumentLinks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (documentL) LoadSourceDocumentDocumentLinks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`document_links`),
		qm.WhereIn(`document_links.source_document_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load document_links")
	}

	var resultSlice []*DocumentLink
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice document_links")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on document_links")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document_links")
	}

	if singular {
		object.R.SourceDocumentDocumentLinks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentLinkR{}
			}
			foreign.R.SourceDocument = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.SourceDocumentID {
				local.R.SourceDocumentDocumentLinks = append(local.R.SourceDocumentDocumentLinks, foreign)
				if foreign.R == nil {
					foreign.R = &documentLinkR{}
				}
				foreign.R.SourceDocument = local
				break
			}
		}
	}

	return nil
}

// LoadTargetDocumentDocumentLinks allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (documentL) LoadTargetDocumentDocumentLinks(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`document_links`),
		qm.WhereIn(`document_links.target_document_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load document_links")
	}

	var resultSlice []*DocumentLink
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice document_links")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on document_links")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document_links")
	}

	if singular {
		object.R.TargetDocumentDocumentLinks = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentLinkR{}
			}
			foreign.R.TargetDocument = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.TargetDocumentID {
				local.R.TargetDocumentDocumentLinks = append(local.R.TargetDocumentDocumentLinks, foreign)
				if foreign.R == nil {
					foreign.R = &documentLinkR{}
				}
				foreign.R.TargetDocument = local
				break
			}
		}
	}

	return nil
}

// LoadDocumentPermissionOverrides allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (documentL) LoadDocumentPermissionOverrides(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`document_permission_overrides`),
		qm.WhereIn(`document_permission_overrides.document_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load document_permission_overrides")
	}

	var resultSlice []*DocumentPermissionOverride
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice document_permission_overrides")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on document_permission_overrides")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document_permission_overrides")
	}

	if singular {
		object.R.DocumentPermissionOverrides = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentPermissionOverrideR{}
			}
			foreign.R.Document = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.DocumentID {
				local.R.DocumentPermissionOverrides = append(local.R.DocumentPermissionOverrides, foreign)
				if foreign.R == nil {
					foreign.R = &documentPermissionOverrideR{}
				}
				foreign.R.Document = local
				break
			}
		}
	}

	return nil
}

// LoadDocumentVersions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (documentL) LoadDocumentVersions(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocument any, mods queries.Applicator) error {
	var slice []*Document
	var object *Document

	if singular {
		var ok bool
		object, ok = maybeDocument.(*Document)
		if !ok {
			object = new(Document)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocument))
			}
		}
	} else {
		s, ok := maybeDocument.(*[]*Document)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocument)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocument))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`document_versions`),
		qm.WhereIn(`document_versions.document_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load document_versions")
	}

	var resultSlice []*DocumentVersion
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice document_versions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on document_versions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for document_versions")
	}

	if singular {
		object.R.DocumentVersions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentVersionR{}
			}
			foreign.R.Document = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.DocumentID {
				local.R.DocumentVersions = append(local.R.DocumentVersions, foreign)
				if foreign.R == nil {
					foreign.R = &documentVersionR{}
				}
				foreign.R.Document = local
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the document to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByDocuments.
func (o *Document) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, documentPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &documentR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByDocuments: DocumentSlice{o},
		}
	} else {
		related.R.CreatedByDocuments = append(related.R.CreatedByDocuments, o)
	}

	return nil
}

// SetFolder of the document to the related item.
// Sets o.R.Folder to related.
// Adds o to related.R.Documents.
func (o *Document) SetFolder(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Folder) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"folder_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FolderID = related.ID
	if o.R == nil {
		o.R = &documentR{
			Folder: related,
		}
	} else {
		o.R.Folder = related
	}

	if related.R == nil {
		related.R = &folderR{
			Documents: DocumentSlice{o},
		}
	} else {
		related.R.Documents = append(related.R.Documents, o)
	}

	return nil
}

// SetOwner of the document to the related item.
// Sets o.R.Owner to related.
// Adds o to related.R.OwnerDocuments.
func (o *Document) SetOwner(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"owner_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.OwnerID, related.ID)
	if o.R == nil {
		o.R = &documentR{
			Owner: related,
		}
	} else {
		o.R.Owner = related
	}

	if related.R == nil {
		related.R = &userR{
			OwnerDocuments: DocumentSlice{o},
		}
	} else {
		related.R.OwnerDocuments = append(related.R.OwnerDocuments, o)
	}

	return nil
}

// RemoveOwner relationship.
// Sets o.R.Owner to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Document) RemoveOwner(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.OwnerID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("owner_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.Owner = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.OwnerDocuments {
		if queries.Equal(o.OwnerID, ri.OwnerID) {
			continue
		}

		ln := len(related.R.OwnerDocuments)
		if ln > 1 && i < ln-1 {
			related.R.OwnerDocuments[i] = related.R.OwnerDocuments[ln-1]
		}
		related.R.OwnerDocuments = related.R.OwnerDocuments[:ln-1]
		break
	}
	return nil
}

// SetUpdatedByUser of the document to the related item.
// Sets o.R.UpdatedByUser to related.
// Adds o to related.R.UpdatedByDocuments.
func (o *Document) SetUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"updated_by"}),
		strmangle.WhereClause("\"", "\"", 2, documentPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UpdatedBy, related.ID)
	if o.R == nil {
		o.R = &documentR{
			UpdatedByUser: related,
		}
	} else {
		o.R.UpdatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UpdatedByDocuments: DocumentSlice{o},
		}
	} else {
		related.R.UpdatedByDocuments = append(related.R.UpdatedByDocuments, o)
	}

	return nil
}

// RemoveUpdatedByUser relationship.
// Sets o.R.UpdatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Document) RemoveUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UpdatedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("updated_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.UpdatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UpdatedByDocuments {
		if queries.Equal(o.UpdatedBy, ri.UpdatedBy) {
			continue
		}

		ln := len(related.R.UpdatedByDocuments)
		if ln > 1 && i < ln-1 {
			related.R.UpdatedByDocuments[i] = related.R.UpdatedByDocuments[ln-1]
		}
		related.R.UpdatedByDocuments = related.R.UpdatedByDocuments[:ln-1]
		break
	}
	return nil
}

// AddDocumentFiles adds the given related objects to the existing relationships
// of the document, optionally inserting them as new records.
// Appends related to o.R.DocumentFiles.
// Sets related.R.Document appropriately.
func (o *Document) AddDocumentFiles(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DocumentFile) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.DocumentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"document_files\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"document_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentFilePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.DocumentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &documentR{
			DocumentFiles: related,
		}
	} else {
		o.R.DocumentFiles = append(o.R.DocumentFiles, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentFileR{
				Document: o,
			}
		} else {
			rel.R.Document = o
		}
	}
	return nil
}

// AddSourceDocumentDocumentLinks adds the given related objects to the existing relationships
// of the document, optionally inserting them as new records.
// Appends related to o.R.SourceDocumentDocumentLinks.
// Sets related.R.SourceDocument appropriately.
func (o *Document) AddSourceDocumentDocumentLinks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DocumentLink) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.SourceDocumentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"document_links\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"source_document_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentLinkPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.SourceDocumentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &documentR{
			SourceDocumentDocumentLinks: related,
		}
	} else {
		o.R.SourceDocumentDocumentLinks = append(o.R.SourceDocumentDocumentLinks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentLinkR{
				SourceDocument: o,
			}
		} else {
			rel.R.SourceDocument = o
		}
	}
	return nil
}

// AddTargetDocumentDocumentLinks adds the given related objects to the existing relationships
// of the document, optionally inserting them as new records.
// Appends related to o.R.TargetDocumentDocumentLinks.
// Sets related.R.TargetDocument appropriately.
func (o *Document) AddTargetDocumentDocumentLinks(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DocumentLink) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.TargetDocumentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"document_links\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"target_document_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentLinkPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.TargetDocumentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &documentR{
			TargetDocumentDocumentLinks: related,
		}
	} else {
		o.R.TargetDocumentDocumentLinks = append(o.R.TargetDocumentDocumentLinks, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentLinkR{
				TargetDocument: o,
			}
		} else {
			rel.R.TargetDocument = o
		}
	}
	return nil
}

// AddDocumentPermissionOverrides adds the given related objects to the existing relationships
// of the document, optionally inserting them as new records.
// Appends related to o.R.DocumentPermissionOverrides.
// Sets related.R.Document appropriately.
func (o *Document) AddDocumentPermissionOverrides(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DocumentPermissionOverride) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.DocumentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"document_permission_overrides\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"document_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentPermissionOverridePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.DocumentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &documentR{
			DocumentPermissionOverrides: related,
		}
	} else {
		o.R.DocumentPermissionOverrides = append(o.R.DocumentPermissionOverrides, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentPermissionOverrideR{
				Document: o,
			}
		} else {
			rel.R.Document = o
		}
	}
	return nil
}

// AddDocumentVersions adds the given related objects to the existing relationships
// of the document, optionally inserting them as new records.
// Appends related to o.R.DocumentVersions.
// Sets related.R.Document appropriately.
func (o *Document) AddDocumentVersions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*DocumentVersion) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.DocumentID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"document_versions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"document_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentVersionPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.DocumentID = o.ID
		}
	}

	if o.R == nil {
		o.R = &documentR{
			DocumentVersions: related,
		}
	} else {
		o.R.DocumentVersions = append(o.R.DocumentVersions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentVersionR{
				Document: o,
			}
		} else {
			rel.R.Document = o
		}
	}
	return nil
}

// Documents retrieves all the records using an executor.
func Documents(mods ...qm.QueryMod) documentQuery {
	mods = append(mods, qm.From("\"documents\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"documents\".*"})
	}

	return documentQuery{q}
}

// FindDocument retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDocument(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Document, error) {
	documentObj := &Document{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"documents\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, documentObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from documents")
	}

	return documentObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Document) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no documents provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	documentInsertCacheMut.RLock()
	cache, cached := documentInsertCache[key]
	documentInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			documentAllColumns,
			documentColumnsWithDefault,
			documentColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, documentGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(documentType, documentMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(documentType, documentMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"documents\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"documents\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into documents")
	}

	if !cached {
		documentInsertCacheMut.Lock()
		documentInsertCache[key] = cache
		documentInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Document.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Document) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	documentUpdateCacheMut.RLock()
	cache, cached := documentUpdateCache[key]
	documentUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			documentAllColumns,
			documentPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, documentGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update documents, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"documents\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, documentPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(documentType, documentMapping, append(wl, documentPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update documents row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for documents")
	}

	if !cached {
		documentUpdateCacheMut.Lock()
		documentUpdateCache[key] = cache
		documentUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q documentQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for documents")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DocumentSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"documents\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, documentPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in document slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all document")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Document) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no documents provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(documentColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	documentUpsertCacheMut.RLock()
	cache, cached := documentUpsertCache[key]
	documentUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			documentAllColumns,
			documentColumnsWithDefault,
			documentColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			documentAllColumns,
			documentPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, documentGeneratedColumns)
		update = strmangle.SetComplement(update, documentGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert documents, could not build update column list")
		}

		ret := strmangle.SetComplement(documentAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(documentPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert documents, could not build conflict column list")
			}

			conflict = make([]string, len(documentPrimaryKeyColumns))
			copy(conflict, documentPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"documents\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(documentType, documentMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(documentType, documentMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert documents")
	}

	if !cached {
		documentUpsertCacheMut.Lock()
		documentUpsertCache[key] = cache
		documentUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Document record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Document) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Document provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), documentPrimaryKeyMapping)
	sql := "DELETE FROM \"documents\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for documents")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q documentQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no documentQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from documents")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for documents")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DocumentSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"documents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from document slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for documents")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Document) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDocument(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DocumentSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DocumentSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"documents\".* FROM \"documents\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DocumentSlice")
	}

	*o = slice

	return nil
}

// DocumentExists checks if the Document row exists.
func DocumentExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"documents\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if documents exists")
	}

	return exists, nil
}

// Exists checks if the Document row exists.
func (o *Document) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DocumentExists(ctx, exec, o.ID)
}
