// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/sqlboiler/v4/types"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// DocumentVersion is an object representing the database table.
type DocumentVersion struct {
	ID            int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	DocumentID    int64      `boil:"document_id" json:"document_id" toml:"document_id" yaml:"document_id"`
	VersionNumber int64      `boil:"version_number" json:"version_number" toml:"version_number" yaml:"version_number"`
	Content       types.JSON `boil:"content" json:"content" toml:"content" yaml:"content"`
	CreatedBy     int64      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	CreatedAt     time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *documentVersionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L documentVersionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var DocumentVersionColumns = struct {
	ID            string
	DocumentID    string
	VersionNumber string
	Content       string
	CreatedBy     string
	CreatedAt     string
}{
	ID:            "id",
	DocumentID:    "document_id",
	VersionNumber: "version_number",
	Content:       "content",
	CreatedBy:     "created_by",
	CreatedAt:     "created_at",
}

var DocumentVersionTableColumns = struct {
	ID            string
	DocumentID    string
	VersionNumber string
	Content       string
	CreatedBy     string
	CreatedAt     string
}{
	ID:            "document_versions.id",
	DocumentID:    "document_versions.document_id",
	VersionNumber: "document_versions.version_number",
	Content:       "document_versions.content",
	CreatedBy:     "document_versions.created_by",
	CreatedAt:     "document_versions.created_at",
}

// Generated where

type whereHelpertypes_JSON struct{ field string }

func (w whereHelpertypes_JSON) EQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.EQ, x)
}
func (w whereHelpertypes_JSON) NEQ(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.NEQ, x)
}
func (w whereHelpertypes_JSON) LT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LT, x)
}
func (w whereHelpertypes_JSON) LTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.LTE, x)
}
func (w whereHelpertypes_JSON) GT(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GT, x)
}
func (w whereHelpertypes_JSON) GTE(x types.JSON) qm.QueryMod {
	return qmhelper.Where(w.field, qmhelper.GTE, x)
}

var DocumentVersionWhere = struct {
	ID            whereHelperint64
	DocumentID    whereHelperint64
	VersionNumber whereHelperint64
	Content       whereHelpertypes_JSON
	CreatedBy     whereHelperint64
	CreatedAt     whereHelpertime_Time
}{
	ID:            whereHelperint64{field: "\"document_versions\".\"id\""},
	DocumentID:    whereHelperint64{field: "\"document_versions\".\"document_id\""},
	VersionNumber: whereHelperint64{field: "\"document_versions\".\"version_number\""},
	Content:       whereHelpertypes_JSON{field: "\"document_versions\".\"content\""},
	CreatedBy:     whereHelperint64{field: "\"document_versions\".\"created_by\""},
	CreatedAt:     whereHelpertime_Time{field: "\"document_versions\".\"created_at\""},
}

// DocumentVersionRels is where relationship names are stored.
var DocumentVersionRels = struct {
	CreatedByUser string
	Document      string
}{
	CreatedByUser: "CreatedByUser",
	Document:      "Document",
}

// documentVersionR is where relationships are stored.
type documentVersionR struct {
	CreatedByUser *User     `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Document      *Document `boil:"Document" json:"Document" toml:"Document" yaml:"Document"`
}

// NewStruct creates a new relationship struct
func (*documentVersionR) NewStruct() *documentVersionR {
	return &documentVersionR{}
}

func (o *DocumentVersion) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *documentVersionR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *DocumentVersion) GetDocument() *Document {
	if o == nil {
		return nil
	}

	return o.R.GetDocument()
}

func (r *documentVersionR) GetDocument() *Document {
	if r == nil {
		return nil
	}

	return r.Document
}

// documentVersionL is where Load methods for each relationship are stored.
type documentVersionL struct{}

var (
	documentVersionAllColumns            = []string{"id", "document_id", "version_number", "content", "created_by", "created_at"}
	documentVersionColumnsWithoutDefault = []string{"document_id", "version_number", "content", "created_by"}
	documentVersionColumnsWithDefault    = []string{"id", "created_at"}
	documentVersionPrimaryKeyColumns     = []string{"id"}
	documentVersionGeneratedColumns      = []string{"id"}
)

type (
	// DocumentVersionSlice is an alias for a slice of pointers to DocumentVersion.
	// This should almost always be used instead of []DocumentVersion.
	DocumentVersionSlice []*DocumentVersion

	documentVersionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	documentVersionType                 = reflect.TypeOf(&DocumentVersion{})
	documentVersionMapping              = queries.MakeStructMapping(documentVersionType)
	documentVersionPrimaryKeyMapping, _ = queries.BindMapping(documentVersionType, documentVersionMapping, documentVersionPrimaryKeyColumns)
	documentVersionInsertCacheMut       sync.RWMutex
	documentVersionInsertCache          = make(map[string]insertCache)
	documentVersionUpdateCacheMut       sync.RWMutex
	documentVersionUpdateCache          = make(map[string]updateCache)
	documentVersionUpsertCacheMut       sync.RWMutex
	documentVersionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single documentVersion record from the query.
func (q documentVersionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*DocumentVersion, error) {
	o := &DocumentVersion{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for document_versions")
	}

	return o, nil
}

// All returns all DocumentVersion records from the query.
func (q documentVersionQuery) All(ctx context.Context, exec boil.ContextExecutor) (DocumentVersionSlice, error) {
	var o []*DocumentVersion

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to DocumentVersion slice")
	}

	return o, nil
}

// Count returns the count of all DocumentVersion records in the query.
func (q documentVersionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count document_versions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q documentVersionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if document_versions exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *DocumentVersion) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Document pointed to by the foreign key.
func (o *DocumentVersion) Document(mods ...qm.QueryMod) documentQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.DocumentID),
	}

	queryMods = append(queryMods, mods...)

	return Documents(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentVersionL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentVersion any, mods queries.Applicator) error {
	var slice []*DocumentVersion
	var object *DocumentVersion

	if singular {
		var ok bool
		object, ok = maybeDocumentVersion.(*DocumentVersion)
		if !ok {
			object = new(DocumentVersion)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentVersion))
			}
		}
	} else {
		s, ok := maybeDocumentVersion.(*[]*DocumentVersion)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentVersion))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentVersionR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentVersionR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByDocumentVersions = append(foreign.R.CreatedByDocumentVersions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByDocumentVersions = append(foreign.R.CreatedByDocumentVersions, local)
				break
			}
		}
	}

	return nil
}

// LoadDocument allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (documentVersionL) LoadDocument(ctx context.Context, e boil.ContextExecutor, singular bool, maybeDocumentVersion any, mods queries.Applicator) error {
	var slice []*DocumentVersion
	var object *DocumentVersion

	if singular {
		var ok bool
		object, ok = maybeDocumentVersion.(*DocumentVersion)
		if !ok {
			object = new(DocumentVersion)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeDocumentVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeDocumentVersion))
			}
		}
	} else {
		s, ok := maybeDocumentVersion.(*[]*DocumentVersion)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeDocumentVersion)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeDocumentVersion))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &documentVersionR{}
		}
		args[object.DocumentID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &documentVersionR{}
			}

			args[obj.DocumentID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`documents`),
		qm.WhereIn(`documents.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Document")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Document")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for documents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for documents")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Document = foreign
		if foreign.R == nil {
			foreign.R = &documentR{}
		}
		foreign.R.DocumentVersions = append(foreign.R.DocumentVersions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.DocumentID == foreign.ID {
				local.R.Document = foreign
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.DocumentVersions = append(foreign.R.DocumentVersions, local)
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the documentVersion to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByDocumentVersions.
func (o *DocumentVersion) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_versions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, documentVersionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &documentVersionR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByDocumentVersions: DocumentVersionSlice{o},
		}
	} else {
		related.R.CreatedByDocumentVersions = append(related.R.CreatedByDocumentVersions, o)
	}

	return nil
}

// SetDocument of the documentVersion to the related item.
// Sets o.R.Document to related.
// Adds o to related.R.DocumentVersions.
func (o *DocumentVersion) SetDocument(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Document) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"document_versions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"document_id"}),
		strmangle.WhereClause("\"", "\"", 2, documentVersionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.DocumentID = related.ID
	if o.R == nil {
		o.R = &documentVersionR{
			Document: related,
		}
	} else {
		o.R.Document = related
	}

	if related.R == nil {
		related.R = &documentR{
			DocumentVersions: DocumentVersionSlice{o},
		}
	} else {
		related.R.DocumentVersions = append(related.R.DocumentVersions, o)
	}

	return nil
}

// DocumentVersions retrieves all the records using an executor.
func DocumentVersions(mods ...qm.QueryMod) documentVersionQuery {
	mods = append(mods, qm.From("\"document_versions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"document_versions\".*"})
	}

	return documentVersionQuery{q}
}

// FindDocumentVersion retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindDocumentVersion(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*DocumentVersion, error) {
	documentVersionObj := &DocumentVersion{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"document_versions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, documentVersionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from document_versions")
	}

	return documentVersionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *DocumentVersion) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no document_versions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentVersionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	documentVersionInsertCacheMut.RLock()
	cache, cached := documentVersionInsertCache[key]
	documentVersionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			documentVersionAllColumns,
			documentVersionColumnsWithDefault,
			documentVersionColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, documentVersionGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(documentVersionType, documentVersionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(documentVersionType, documentVersionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"document_versions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"document_versions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into document_versions")
	}

	if !cached {
		documentVersionInsertCacheMut.Lock()
		documentVersionInsertCache[key] = cache
		documentVersionInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the DocumentVersion.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *DocumentVersion) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	documentVersionUpdateCacheMut.RLock()
	cache, cached := documentVersionUpdateCache[key]
	documentVersionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			documentVersionAllColumns,
			documentVersionPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, documentVersionGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update document_versions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"document_versions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, documentVersionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(documentVersionType, documentVersionMapping, append(wl, documentVersionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update document_versions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for document_versions")
	}

	if !cached {
		documentVersionUpdateCacheMut.Lock()
		documentVersionUpdateCache[key] = cache
		documentVersionUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q documentVersionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for document_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for document_versions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o DocumentVersionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"document_versions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, documentVersionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in documentVersion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all documentVersion")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *DocumentVersion) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no document_versions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(documentVersionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	documentVersionUpsertCacheMut.RLock()
	cache, cached := documentVersionUpsertCache[key]
	documentVersionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			documentVersionAllColumns,
			documentVersionColumnsWithDefault,
			documentVersionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			documentVersionAllColumns,
			documentVersionPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, documentVersionGeneratedColumns)
		update = strmangle.SetComplement(update, documentVersionGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert document_versions, could not build update column list")
		}

		ret := strmangle.SetComplement(documentVersionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(documentVersionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert document_versions, could not build conflict column list")
			}

			conflict = make([]string, len(documentVersionPrimaryKeyColumns))
			copy(conflict, documentVersionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"document_versions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(documentVersionType, documentVersionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(documentVersionType, documentVersionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert document_versions")
	}

	if !cached {
		documentVersionUpsertCacheMut.Lock()
		documentVersionUpsertCache[key] = cache
		documentVersionUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single DocumentVersion record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *DocumentVersion) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no DocumentVersion provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), documentVersionPrimaryKeyMapping)
	sql := "DELETE FROM \"document_versions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from document_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for document_versions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q documentVersionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no documentVersionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from document_versions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_versions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o DocumentVersionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"document_versions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentVersionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from documentVersion slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for document_versions")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *DocumentVersion) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindDocumentVersion(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *DocumentVersionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := DocumentVersionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), documentVersionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"document_versions\".* FROM \"document_versions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, documentVersionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in DocumentVersionSlice")
	}

	*o = slice

	return nil
}

// DocumentVersionExists checks if the DocumentVersion row exists.
func DocumentVersionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"document_versions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if document_versions exists")
	}

	return exists, nil
}

// Exists checks if the DocumentVersion row exists.
func (o *DocumentVersion) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return DocumentVersionExists(ctx, exec, o.ID)
}
