// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// Folder is an object representing the database table.
type Folder struct {
	ID             int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	PortalID       int64      `boil:"portal_id" json:"portal_id" toml:"portal_id" yaml:"portal_id"`
	ParentFolderID null.Int64 `boil:"parent_folder_id" json:"parent_folder_id,omitempty" toml:"parent_folder_id" yaml:"parent_folder_id,omitempty"`
	Name           string     `boil:"name" json:"name" toml:"name" yaml:"name"`
	CreatedBy      int64      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	UpdatedBy      null.Int64 `boil:"updated_by" json:"updated_by,omitempty" toml:"updated_by" yaml:"updated_by,omitempty"`
	CreatedAt      time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt      time.Time  `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *folderR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L folderL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FolderColumns = struct {
	ID             string
	PortalID       string
	ParentFolderID string
	Name           string
	CreatedBy      string
	UpdatedBy      string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "id",
	PortalID:       "portal_id",
	ParentFolderID: "parent_folder_id",
	Name:           "name",
	CreatedBy:      "created_by",
	UpdatedBy:      "updated_by",
	CreatedAt:      "created_at",
	UpdatedAt:      "updated_at",
}

var FolderTableColumns = struct {
	ID             string
	PortalID       string
	ParentFolderID string
	Name           string
	CreatedBy      string
	UpdatedBy      string
	CreatedAt      string
	UpdatedAt      string
}{
	ID:             "folders.id",
	PortalID:       "folders.portal_id",
	ParentFolderID: "folders.parent_folder_id",
	Name:           "folders.name",
	CreatedBy:      "folders.created_by",
	UpdatedBy:      "folders.updated_by",
	CreatedAt:      "folders.created_at",
	UpdatedAt:      "folders.updated_at",
}

// Generated where

var FolderWhere = struct {
	ID             whereHelperint64
	PortalID       whereHelperint64
	ParentFolderID whereHelpernull_Int64
	Name           whereHelperstring
	CreatedBy      whereHelperint64
	UpdatedBy      whereHelpernull_Int64
	CreatedAt      whereHelpertime_Time
	UpdatedAt      whereHelpertime_Time
}{
	ID:             whereHelperint64{field: "\"folders\".\"id\""},
	PortalID:       whereHelperint64{field: "\"folders\".\"portal_id\""},
	ParentFolderID: whereHelpernull_Int64{field: "\"folders\".\"parent_folder_id\""},
	Name:           whereHelperstring{field: "\"folders\".\"name\""},
	CreatedBy:      whereHelperint64{field: "\"folders\".\"created_by\""},
	UpdatedBy:      whereHelpernull_Int64{field: "\"folders\".\"updated_by\""},
	CreatedAt:      whereHelpertime_Time{field: "\"folders\".\"created_at\""},
	UpdatedAt:      whereHelpertime_Time{field: "\"folders\".\"updated_at\""},
}

// FolderRels is where relationship names are stored.
var FolderRels = struct {
	CreatedByUser             string
	ParentFolder              string
	Portal                    string
	UpdatedByUser             string
	Documents                 string
	FolderPermissionOverrides string
	ParentFolderFolders       string
}{
	CreatedByUser:             "CreatedByUser",
	ParentFolder:              "ParentFolder",
	Portal:                    "Portal",
	UpdatedByUser:             "UpdatedByUser",
	Documents:                 "Documents",
	FolderPermissionOverrides: "FolderPermissionOverrides",
	ParentFolderFolders:       "ParentFolderFolders",
}

// folderR is where relationships are stored.
type folderR struct {
	CreatedByUser             *User                         `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	ParentFolder              *Folder                       `boil:"ParentFolder" json:"ParentFolder" toml:"ParentFolder" yaml:"ParentFolder"`
	Portal                    *Portal                       `boil:"Portal" json:"Portal" toml:"Portal" yaml:"Portal"`
	UpdatedByUser             *User                         `boil:"UpdatedByUser" json:"UpdatedByUser" toml:"UpdatedByUser" yaml:"UpdatedByUser"`
	Documents                 DocumentSlice                 `boil:"Documents" json:"Documents" toml:"Documents" yaml:"Documents"`
	FolderPermissionOverrides FolderPermissionOverrideSlice `boil:"FolderPermissionOverrides" json:"FolderPermissionOverrides" toml:"FolderPermissionOverrides" yaml:"FolderPermissionOverrides"`
	ParentFolderFolders       FolderSlice                   `boil:"ParentFolderFolders" json:"ParentFolderFolders" toml:"ParentFolderFolders" yaml:"ParentFolderFolders"`
}

// NewStruct creates a new relationship struct
func (*folderR) NewStruct() *folderR {
	return &folderR{}
}

func (o *Folder) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *folderR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *Folder) GetParentFolder() *Folder {
	if o == nil {
		return nil
	}

	return o.R.GetParentFolder()
}

func (r *folderR) GetParentFolder() *Folder {
	if r == nil {
		return nil
	}

	return r.ParentFolder
}

func (o *Folder) GetPortal() *Portal {
	if o == nil {
		return nil
	}

	return o.R.GetPortal()
}

func (r *folderR) GetPortal() *Portal {
	if r == nil {
		return nil
	}

	return r.Portal
}

func (o *Folder) GetUpdatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUpdatedByUser()
}

func (r *folderR) GetUpdatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.UpdatedByUser
}

func (o *Folder) GetDocuments() DocumentSlice {
	if o == nil {
		return nil
	}

	return o.R.GetDocuments()
}

func (r *folderR) GetDocuments() DocumentSlice {
	if r == nil {
		return nil
	}

	return r.Documents
}

func (o *Folder) GetFolderPermissionOverrides() FolderPermissionOverrideSlice {
	if o == nil {
		return nil
	}

	return o.R.GetFolderPermissionOverrides()
}

func (r *folderR) GetFolderPermissionOverrides() FolderPermissionOverrideSlice {
	if r == nil {
		return nil
	}

	return r.FolderPermissionOverrides
}

func (o *Folder) GetParentFolderFolders() FolderSlice {
	if o == nil {
		return nil
	}

	return o.R.GetParentFolderFolders()
}

func (r *folderR) GetParentFolderFolders() FolderSlice {
	if r == nil {
		return nil
	}

	return r.ParentFolderFolders
}

// folderL is where Load methods for each relationship are stored.
type folderL struct{}

var (
	folderAllColumns            = []string{"id", "portal_id", "parent_folder_id", "name", "created_by", "updated_by", "created_at", "updated_at"}
	folderColumnsWithoutDefault = []string{"portal_id", "name", "created_by"}
	folderColumnsWithDefault    = []string{"id", "parent_folder_id", "updated_by", "created_at", "updated_at"}
	folderPrimaryKeyColumns     = []string{"id"}
	folderGeneratedColumns      = []string{"id"}
)

type (
	// FolderSlice is an alias for a slice of pointers to Folder.
	// This should almost always be used instead of []Folder.
	FolderSlice []*Folder

	folderQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	folderType                 = reflect.TypeOf(&Folder{})
	folderMapping              = queries.MakeStructMapping(folderType)
	folderPrimaryKeyMapping, _ = queries.BindMapping(folderType, folderMapping, folderPrimaryKeyColumns)
	folderInsertCacheMut       sync.RWMutex
	folderInsertCache          = make(map[string]insertCache)
	folderUpdateCacheMut       sync.RWMutex
	folderUpdateCache          = make(map[string]updateCache)
	folderUpsertCacheMut       sync.RWMutex
	folderUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single folder record from the query.
func (q folderQuery) One(ctx context.Context, exec boil.ContextExecutor) (*Folder, error) {
	o := &Folder{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for folders")
	}

	return o, nil
}

// All returns all Folder records from the query.
func (q folderQuery) All(ctx context.Context, exec boil.ContextExecutor) (FolderSlice, error) {
	var o []*Folder

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to Folder slice")
	}

	return o, nil
}

// Count returns the count of all Folder records in the query.
func (q folderQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count folders rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q folderQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if folders exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *Folder) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// ParentFolder pointed to by the foreign key.
func (o *Folder) ParentFolder(mods ...qm.QueryMod) folderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.ParentFolderID),
	}

	queryMods = append(queryMods, mods...)

	return Folders(queryMods...)
}

// Portal pointed to by the foreign key.
func (o *Folder) Portal(mods ...qm.QueryMod) portalQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PortalID),
	}

	queryMods = append(queryMods, mods...)

	return Portals(queryMods...)
}

// UpdatedByUser pointed to by the foreign key.
func (o *Folder) UpdatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UpdatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Documents retrieves all the document's Documents with an executor.
func (o *Folder) Documents(mods ...qm.QueryMod) documentQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"documents\".\"folder_id\"=?", o.ID),
	)

	return Documents(queryMods...)
}

// FolderPermissionOverrides retrieves all the folder_permission_override's FolderPermissionOverrides with an executor.
func (o *Folder) FolderPermissionOverrides(mods ...qm.QueryMod) folderPermissionOverrideQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"folder_permission_overrides\".\"folder_id\"=?", o.ID),
	)

	return FolderPermissionOverrides(queryMods...)
}

// ParentFolderFolders retrieves all the folder's Folders with an executor via parent_folder_id column.
func (o *Folder) ParentFolderFolders(mods ...qm.QueryMod) folderQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"folders\".\"parent_folder_id\"=?", o.ID),
	)

	return Folders(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByFolders = append(foreign.R.CreatedByFolders, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByFolders = append(foreign.R.CreatedByFolders, local)
				break
			}
		}
	}

	return nil
}

// LoadParentFolder allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderL) LoadParentFolder(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		if !queries.IsNil(object.ParentFolderID) {
			args[object.ParentFolderID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}

			if !queries.IsNil(obj.ParentFolderID) {
				args[obj.ParentFolderID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folders`),
		qm.WhereIn(`folders.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Folder")
	}

	var resultSlice []*Folder
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Folder")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for folders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folders")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.ParentFolder = foreign
		if foreign.R == nil {
			foreign.R = &folderR{}
		}
		foreign.R.ParentFolderFolders = append(foreign.R.ParentFolderFolders, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.ParentFolderID, foreign.ID) {
				local.R.ParentFolder = foreign
				if foreign.R == nil {
					foreign.R = &folderR{}
				}
				foreign.R.ParentFolderFolders = append(foreign.R.ParentFolderFolders, local)
				break
			}
		}
	}

	return nil
}

// LoadPortal allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderL) LoadPortal(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		args[object.PortalID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}

			args[obj.PortalID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`portals`),
		qm.WhereIn(`portals.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Portal")
	}

	var resultSlice []*Portal
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Portal")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for portals")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for portals")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Portal = foreign
		if foreign.R == nil {
			foreign.R = &portalR{}
		}
		foreign.R.Folders = append(foreign.R.Folders, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PortalID == foreign.ID {
				local.R.Portal = foreign
				if foreign.R == nil {
					foreign.R = &portalR{}
				}
				foreign.R.Folders = append(foreign.R.Folders, local)
				break
			}
		}
	}

	return nil
}

// LoadUpdatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderL) LoadUpdatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		if !queries.IsNil(object.UpdatedBy) {
			args[object.UpdatedBy] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}

			if !queries.IsNil(obj.UpdatedBy) {
				args[obj.UpdatedBy] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.UpdatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.UpdatedByFolders = append(foreign.R.UpdatedByFolders, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UpdatedBy, foreign.ID) {
				local.R.UpdatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.UpdatedByFolders = append(foreign.R.UpdatedByFolders, local)
				break
			}
		}
	}

	return nil
}

// LoadDocuments allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (folderL) LoadDocuments(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`documents`),
		qm.WhereIn(`documents.folder_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load documents")
	}

	var resultSlice []*Document
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice documents")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on documents")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for documents")
	}

	if singular {
		object.R.Documents = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &documentR{}
			}
			foreign.R.Folder = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FolderID {
				local.R.Documents = append(local.R.Documents, foreign)
				if foreign.R == nil {
					foreign.R = &documentR{}
				}
				foreign.R.Folder = local
				break
			}
		}
	}

	return nil
}

// LoadFolderPermissionOverrides allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (folderL) LoadFolderPermissionOverrides(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folder_permission_overrides`),
		qm.WhereIn(`folder_permission_overrides.folder_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load folder_permission_overrides")
	}

	var resultSlice []*FolderPermissionOverride
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice folder_permission_overrides")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on folder_permission_overrides")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folder_permission_overrides")
	}

	if singular {
		object.R.FolderPermissionOverrides = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &folderPermissionOverrideR{}
			}
			foreign.R.Folder = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.FolderID {
				local.R.FolderPermissionOverrides = append(local.R.FolderPermissionOverrides, foreign)
				if foreign.R == nil {
					foreign.R = &folderPermissionOverrideR{}
				}
				foreign.R.Folder = local
				break
			}
		}
	}

	return nil
}

// LoadParentFolderFolders allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (folderL) LoadParentFolderFolders(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolder any, mods queries.Applicator) error {
	var slice []*Folder
	var object *Folder

	if singular {
		var ok bool
		object, ok = maybeFolder.(*Folder)
		if !ok {
			object = new(Folder)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolder))
			}
		}
	} else {
		s, ok := maybeFolder.(*[]*Folder)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolder)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolder))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folders`),
		qm.WhereIn(`folders.parent_folder_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load folders")
	}

	var resultSlice []*Folder
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice folders")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on folders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folders")
	}

	if singular {
		object.R.ParentFolderFolders = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &folderR{}
			}
			foreign.R.ParentFolder = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if queries.Equal(local.ID, foreign.ParentFolderID) {
				local.R.ParentFolderFolders = append(local.R.ParentFolderFolders, foreign)
				if foreign.R == nil {
					foreign.R = &folderR{}
				}
				foreign.R.ParentFolder = local
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the folder to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByFolders.
func (o *Folder) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folders\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, folderPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &folderR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByFolders: FolderSlice{o},
		}
	} else {
		related.R.CreatedByFolders = append(related.R.CreatedByFolders, o)
	}

	return nil
}

// SetParentFolder of the folder to the related item.
// Sets o.R.ParentFolder to related.
// Adds o to related.R.ParentFolderFolders.
func (o *Folder) SetParentFolder(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Folder) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folders\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"parent_folder_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.ParentFolderID, related.ID)
	if o.R == nil {
		o.R = &folderR{
			ParentFolder: related,
		}
	} else {
		o.R.ParentFolder = related
	}

	if related.R == nil {
		related.R = &folderR{
			ParentFolderFolders: FolderSlice{o},
		}
	} else {
		related.R.ParentFolderFolders = append(related.R.ParentFolderFolders, o)
	}

	return nil
}

// RemoveParentFolder relationship.
// Sets o.R.ParentFolder to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Folder) RemoveParentFolder(ctx context.Context, exec boil.ContextExecutor, related *Folder) error {
	var err error

	queries.SetScanner(&o.ParentFolderID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("parent_folder_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.ParentFolder = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.ParentFolderFolders {
		if queries.Equal(o.ParentFolderID, ri.ParentFolderID) {
			continue
		}

		ln := len(related.R.ParentFolderFolders)
		if ln > 1 && i < ln-1 {
			related.R.ParentFolderFolders[i] = related.R.ParentFolderFolders[ln-1]
		}
		related.R.ParentFolderFolders = related.R.ParentFolderFolders[:ln-1]
		break
	}
	return nil
}

// SetPortal of the folder to the related item.
// Sets o.R.Portal to related.
// Adds o to related.R.Folders.
func (o *Folder) SetPortal(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Portal) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folders\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"portal_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PortalID = related.ID
	if o.R == nil {
		o.R = &folderR{
			Portal: related,
		}
	} else {
		o.R.Portal = related
	}

	if related.R == nil {
		related.R = &portalR{
			Folders: FolderSlice{o},
		}
	} else {
		related.R.Folders = append(related.R.Folders, o)
	}

	return nil
}

// SetUpdatedByUser of the folder to the related item.
// Sets o.R.UpdatedByUser to related.
// Adds o to related.R.UpdatedByFolders.
func (o *Folder) SetUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folders\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"updated_by"}),
		strmangle.WhereClause("\"", "\"", 2, folderPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UpdatedBy, related.ID)
	if o.R == nil {
		o.R = &folderR{
			UpdatedByUser: related,
		}
	} else {
		o.R.UpdatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			UpdatedByFolders: FolderSlice{o},
		}
	} else {
		related.R.UpdatedByFolders = append(related.R.UpdatedByFolders, o)
	}

	return nil
}

// RemoveUpdatedByUser relationship.
// Sets o.R.UpdatedByUser to nil.
// Removes o from all passed in related items' relationships struct.
func (o *Folder) RemoveUpdatedByUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UpdatedBy, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("updated_by")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.UpdatedByUser = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.UpdatedByFolders {
		if queries.Equal(o.UpdatedBy, ri.UpdatedBy) {
			continue
		}

		ln := len(related.R.UpdatedByFolders)
		if ln > 1 && i < ln-1 {
			related.R.UpdatedByFolders[i] = related.R.UpdatedByFolders[ln-1]
		}
		related.R.UpdatedByFolders = related.R.UpdatedByFolders[:ln-1]
		break
	}
	return nil
}

// AddDocuments adds the given related objects to the existing relationships
// of the folder, optionally inserting them as new records.
// Appends related to o.R.Documents.
// Sets related.R.Folder appropriately.
func (o *Folder) AddDocuments(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Document) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FolderID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"documents\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"folder_id"}),
				strmangle.WhereClause("\"", "\"", 2, documentPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FolderID = o.ID
		}
	}

	if o.R == nil {
		o.R = &folderR{
			Documents: related,
		}
	} else {
		o.R.Documents = append(o.R.Documents, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &documentR{
				Folder: o,
			}
		} else {
			rel.R.Folder = o
		}
	}
	return nil
}

// AddFolderPermissionOverrides adds the given related objects to the existing relationships
// of the folder, optionally inserting them as new records.
// Appends related to o.R.FolderPermissionOverrides.
// Sets related.R.Folder appropriately.
func (o *Folder) AddFolderPermissionOverrides(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*FolderPermissionOverride) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.FolderID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"folder_permission_overrides\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"folder_id"}),
				strmangle.WhereClause("\"", "\"", 2, folderPermissionOverridePrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.FolderID = o.ID
		}
	}

	if o.R == nil {
		o.R = &folderR{
			FolderPermissionOverrides: related,
		}
	} else {
		o.R.FolderPermissionOverrides = append(o.R.FolderPermissionOverrides, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &folderPermissionOverrideR{
				Folder: o,
			}
		} else {
			rel.R.Folder = o
		}
	}
	return nil
}

// AddParentFolderFolders adds the given related objects to the existing relationships
// of the folder, optionally inserting them as new records.
// Appends related to o.R.ParentFolderFolders.
// Sets related.R.ParentFolder appropriately.
func (o *Folder) AddParentFolderFolders(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Folder) error {
	var err error
	for _, rel := range related {
		if insert {
			queries.Assign(&rel.ParentFolderID, o.ID)
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"folders\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"parent_folder_id"}),
				strmangle.WhereClause("\"", "\"", 2, folderPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			queries.Assign(&rel.ParentFolderID, o.ID)
		}
	}

	if o.R == nil {
		o.R = &folderR{
			ParentFolderFolders: related,
		}
	} else {
		o.R.ParentFolderFolders = append(o.R.ParentFolderFolders, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &folderR{
				ParentFolder: o,
			}
		} else {
			rel.R.ParentFolder = o
		}
	}
	return nil
}

// SetParentFolderFolders removes all previously related items of the
// folder replacing them completely with the passed
// in related items, optionally inserting them as new records.
// Sets o.R.ParentFolder's ParentFolderFolders accordingly.
// Replaces o.R.ParentFolderFolders with related.
// Sets related.R.ParentFolder's ParentFolderFolders accordingly.
func (o *Folder) SetParentFolderFolders(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*Folder) error {
	query := "update \"folders\" set \"parent_folder_id\" = null where \"parent_folder_id\" = $1"
	values := []any{o.ID}
	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, query)
		fmt.Fprintln(writer, values)
	}
	_, err := exec.ExecContext(ctx, query, values...)
	if err != nil {
		return errors.Wrap(err, "failed to remove relationships before set")
	}

	if o.R != nil {
		for _, rel := range o.R.ParentFolderFolders {
			queries.SetScanner(&rel.ParentFolderID, nil)
			if rel.R == nil {
				continue
			}

			rel.R.ParentFolder = nil
		}
		o.R.ParentFolderFolders = nil
	}

	return o.AddParentFolderFolders(ctx, exec, insert, related...)
}

// RemoveParentFolderFolders relationships from objects passed in.
// Removes related items from R.ParentFolderFolders (uses pointer comparison, removal does not keep order)
// Sets related.R.ParentFolder.
func (o *Folder) RemoveParentFolderFolders(ctx context.Context, exec boil.ContextExecutor, related ...*Folder) error {
	if len(related) == 0 {
		return nil
	}

	var err error
	for _, rel := range related {
		queries.SetScanner(&rel.ParentFolderID, nil)
		if rel.R != nil {
			rel.R.ParentFolder = nil
		}
		if _, err = rel.Update(ctx, exec, boil.Whitelist("parent_folder_id")); err != nil {
			return err
		}
	}
	if o.R == nil {
		return nil
	}

	for _, rel := range related {
		for i, ri := range o.R.ParentFolderFolders {
			if rel != ri {
				continue
			}

			ln := len(o.R.ParentFolderFolders)
			if ln > 1 && i < ln-1 {
				o.R.ParentFolderFolders[i] = o.R.ParentFolderFolders[ln-1]
			}
			o.R.ParentFolderFolders = o.R.ParentFolderFolders[:ln-1]
			break
		}
	}

	return nil
}

// Folders retrieves all the records using an executor.
func Folders(mods ...qm.QueryMod) folderQuery {
	mods = append(mods, qm.From("\"folders\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"folders\".*"})
	}

	return folderQuery{q}
}

// FindFolder retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFolder(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*Folder, error) {
	folderObj := &Folder{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"folders\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, folderObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from folders")
	}

	return folderObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *Folder) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no folders provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(folderColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	folderInsertCacheMut.RLock()
	cache, cached := folderInsertCache[key]
	folderInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			folderAllColumns,
			folderColumnsWithDefault,
			folderColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, folderGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(folderType, folderMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(folderType, folderMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"folders\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"folders\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into folders")
	}

	if !cached {
		folderInsertCacheMut.Lock()
		folderInsertCache[key] = cache
		folderInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the Folder.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *Folder) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	folderUpdateCacheMut.RLock()
	cache, cached := folderUpdateCache[key]
	folderUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			folderAllColumns,
			folderPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, folderGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update folders, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"folders\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, folderPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(folderType, folderMapping, append(wl, folderPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update folders row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for folders")
	}

	if !cached {
		folderUpdateCacheMut.Lock()
		folderUpdateCache[key] = cache
		folderUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q folderQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for folders")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for folders")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FolderSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"folders\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, folderPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in folder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all folder")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *Folder) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no folders provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(folderColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	folderUpsertCacheMut.RLock()
	cache, cached := folderUpsertCache[key]
	folderUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			folderAllColumns,
			folderColumnsWithDefault,
			folderColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			folderAllColumns,
			folderPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, folderGeneratedColumns)
		update = strmangle.SetComplement(update, folderGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert folders, could not build update column list")
		}

		ret := strmangle.SetComplement(folderAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(folderPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert folders, could not build conflict column list")
			}

			conflict = make([]string, len(folderPrimaryKeyColumns))
			copy(conflict, folderPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"folders\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(folderType, folderMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(folderType, folderMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert folders")
	}

	if !cached {
		folderUpsertCacheMut.Lock()
		folderUpsertCache[key] = cache
		folderUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single Folder record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *Folder) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no Folder provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), folderPrimaryKeyMapping)
	sql := "DELETE FROM \"folders\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from folders")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for folders")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q folderQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no folderQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from folders")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for folders")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FolderSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"folders\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, folderPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from folder slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for folders")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *Folder) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFolder(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FolderSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FolderSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"folders\".* FROM \"folders\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, folderPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FolderSlice")
	}

	*o = slice

	return nil
}

// FolderExists checks if the Folder row exists.
func FolderExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"folders\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if folders exists")
	}

	return exists, nil
}

// Exists checks if the Folder row exists.
func (o *Folder) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FolderExists(ctx, exec, o.ID)
}
