// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// FolderPermission is an object representing the database table.
type FolderPermission struct {
	ID           int64      `boil:"id" json:"id" toml:"id" yaml:"id"`
	FolderID     int64      `boil:"folder_id" json:"folder_id" toml:"folder_id" yaml:"folder_id"`
	PortalRoleID null.Int64 `boil:"portal_role_id" json:"portal_role_id,omitempty" toml:"portal_role_id" yaml:"portal_role_id,omitempty"`
	UserID       null.Int64 `boil:"user_id" json:"user_id,omitempty" toml:"user_id" yaml:"user_id,omitempty"`
	PermissionID int64      `boil:"permission_id" json:"permission_id" toml:"permission_id" yaml:"permission_id"`
	CreatedBy    int64      `boil:"created_by" json:"created_by" toml:"created_by" yaml:"created_by"`
	CreatedAt    time.Time  `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`

	R *folderPermissionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L folderPermissionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var FolderPermissionColumns = struct {
	ID           string
	FolderID     string
	PortalRoleID string
	UserID       string
	PermissionID string
	CreatedBy    string
	CreatedAt    string
}{
	ID:           "id",
	FolderID:     "folder_id",
	PortalRoleID: "portal_role_id",
	UserID:       "user_id",
	PermissionID: "permission_id",
	CreatedBy:    "created_by",
	CreatedAt:    "created_at",
}

var FolderPermissionTableColumns = struct {
	ID           string
	FolderID     string
	PortalRoleID string
	UserID       string
	PermissionID string
	CreatedBy    string
	CreatedAt    string
}{
	ID:           "folder_permissions.id",
	FolderID:     "folder_permissions.folder_id",
	PortalRoleID: "folder_permissions.portal_role_id",
	UserID:       "folder_permissions.user_id",
	PermissionID: "folder_permissions.permission_id",
	CreatedBy:    "folder_permissions.created_by",
	CreatedAt:    "folder_permissions.created_at",
}

// Generated where

var FolderPermissionWhere = struct {
	ID           whereHelperint64
	FolderID     whereHelperint64
	PortalRoleID whereHelpernull_Int64
	UserID       whereHelpernull_Int64
	PermissionID whereHelperint64
	CreatedBy    whereHelperint64
	CreatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"folder_permissions\".\"id\""},
	FolderID:     whereHelperint64{field: "\"folder_permissions\".\"folder_id\""},
	PortalRoleID: whereHelpernull_Int64{field: "\"folder_permissions\".\"portal_role_id\""},
	UserID:       whereHelpernull_Int64{field: "\"folder_permissions\".\"user_id\""},
	PermissionID: whereHelperint64{field: "\"folder_permissions\".\"permission_id\""},
	CreatedBy:    whereHelperint64{field: "\"folder_permissions\".\"created_by\""},
	CreatedAt:    whereHelpertime_Time{field: "\"folder_permissions\".\"created_at\""},
}

// FolderPermissionRels is where relationship names are stored.
var FolderPermissionRels = struct {
	CreatedByUser string
	Folder        string
	Permission    string
	PortalRole    string
	User          string
}{
	CreatedByUser: "CreatedByUser",
	Folder:        "Folder",
	Permission:    "Permission",
	PortalRole:    "PortalRole",
	User:          "User",
}

// folderPermissionR is where relationships are stored.
type folderPermissionR struct {
	CreatedByUser *User                 `boil:"CreatedByUser" json:"CreatedByUser" toml:"CreatedByUser" yaml:"CreatedByUser"`
	Folder        *Folder               `boil:"Folder" json:"Folder" toml:"Folder" yaml:"Folder"`
	Permission    *PermissionDefinition `boil:"Permission" json:"Permission" toml:"Permission" yaml:"Permission"`
	PortalRole    *PortalRole           `boil:"PortalRole" json:"PortalRole" toml:"PortalRole" yaml:"PortalRole"`
	User          *User                 `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*folderPermissionR) NewStruct() *folderPermissionR {
	return &folderPermissionR{}
}

func (o *FolderPermission) GetCreatedByUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetCreatedByUser()
}

func (r *folderPermissionR) GetCreatedByUser() *User {
	if r == nil {
		return nil
	}

	return r.CreatedByUser
}

func (o *FolderPermission) GetFolder() *Folder {
	if o == nil {
		return nil
	}

	return o.R.GetFolder()
}

func (r *folderPermissionR) GetFolder() *Folder {
	if r == nil {
		return nil
	}

	return r.Folder
}

func (o *FolderPermission) GetPermission() *PermissionDefinition {
	if o == nil {
		return nil
	}

	return o.R.GetPermission()
}

func (r *folderPermissionR) GetPermission() *PermissionDefinition {
	if r == nil {
		return nil
	}

	return r.Permission
}

func (o *FolderPermission) GetPortalRole() *PortalRole {
	if o == nil {
		return nil
	}

	return o.R.GetPortalRole()
}

func (r *folderPermissionR) GetPortalRole() *PortalRole {
	if r == nil {
		return nil
	}

	return r.PortalRole
}

func (o *FolderPermission) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *folderPermissionR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// folderPermissionL is where Load methods for each relationship are stored.
type folderPermissionL struct{}

var (
	folderPermissionAllColumns            = []string{"id", "folder_id", "portal_role_id", "user_id", "permission_id", "created_by", "created_at"}
	folderPermissionColumnsWithoutDefault = []string{"folder_id", "permission_id", "created_by"}
	folderPermissionColumnsWithDefault    = []string{"id", "portal_role_id", "user_id", "created_at"}
	folderPermissionPrimaryKeyColumns     = []string{"id"}
	folderPermissionGeneratedColumns      = []string{"id"}
)

type (
	// FolderPermissionSlice is an alias for a slice of pointers to FolderPermission.
	// This should almost always be used instead of []FolderPermission.
	FolderPermissionSlice []*FolderPermission

	folderPermissionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	folderPermissionType                 = reflect.TypeOf(&FolderPermission{})
	folderPermissionMapping              = queries.MakeStructMapping(folderPermissionType)
	folderPermissionPrimaryKeyMapping, _ = queries.BindMapping(folderPermissionType, folderPermissionMapping, folderPermissionPrimaryKeyColumns)
	folderPermissionInsertCacheMut       sync.RWMutex
	folderPermissionInsertCache          = make(map[string]insertCache)
	folderPermissionUpdateCacheMut       sync.RWMutex
	folderPermissionUpdateCache          = make(map[string]updateCache)
	folderPermissionUpsertCacheMut       sync.RWMutex
	folderPermissionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single folderPermission record from the query.
func (q folderPermissionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*FolderPermission, error) {
	o := &FolderPermission{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for folder_permissions")
	}

	return o, nil
}

// All returns all FolderPermission records from the query.
func (q folderPermissionQuery) All(ctx context.Context, exec boil.ContextExecutor) (FolderPermissionSlice, error) {
	var o []*FolderPermission

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to FolderPermission slice")
	}

	return o, nil
}

// Count returns the count of all FolderPermission records in the query.
func (q folderPermissionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count folder_permissions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q folderPermissionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if folder_permissions exists")
	}

	return count > 0, nil
}

// CreatedByUser pointed to by the foreign key.
func (o *FolderPermission) CreatedByUser(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.CreatedBy),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// Folder pointed to by the foreign key.
func (o *FolderPermission) Folder(mods ...qm.QueryMod) folderQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.FolderID),
	}

	queryMods = append(queryMods, mods...)

	return Folders(queryMods...)
}

// Permission pointed to by the foreign key.
func (o *FolderPermission) Permission(mods ...qm.QueryMod) permissionDefinitionQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PermissionID),
	}

	queryMods = append(queryMods, mods...)

	return PermissionDefinitions(queryMods...)
}

// PortalRole pointed to by the foreign key.
func (o *FolderPermission) PortalRole(mods ...qm.QueryMod) portalRoleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PortalRoleID),
	}

	queryMods = append(queryMods, mods...)

	return PortalRoles(queryMods...)
}

// User pointed to by the foreign key.
func (o *FolderPermission) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadCreatedByUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderPermissionL) LoadCreatedByUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolderPermission any, mods queries.Applicator) error {
	var slice []*FolderPermission
	var object *FolderPermission

	if singular {
		var ok bool
		object, ok = maybeFolderPermission.(*FolderPermission)
		if !ok {
			object = new(FolderPermission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolderPermission))
			}
		}
	} else {
		s, ok := maybeFolderPermission.(*[]*FolderPermission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolderPermission))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderPermissionR{}
		}
		args[object.CreatedBy] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderPermissionR{}
			}

			args[obj.CreatedBy] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.CreatedByUser = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.CreatedByFolderPermissions = append(foreign.R.CreatedByFolderPermissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.CreatedBy == foreign.ID {
				local.R.CreatedByUser = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.CreatedByFolderPermissions = append(foreign.R.CreatedByFolderPermissions, local)
				break
			}
		}
	}

	return nil
}

// LoadFolder allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderPermissionL) LoadFolder(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolderPermission any, mods queries.Applicator) error {
	var slice []*FolderPermission
	var object *FolderPermission

	if singular {
		var ok bool
		object, ok = maybeFolderPermission.(*FolderPermission)
		if !ok {
			object = new(FolderPermission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolderPermission))
			}
		}
	} else {
		s, ok := maybeFolderPermission.(*[]*FolderPermission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolderPermission))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderPermissionR{}
		}
		args[object.FolderID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderPermissionR{}
			}

			args[obj.FolderID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folders`),
		qm.WhereIn(`folders.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Folder")
	}

	var resultSlice []*Folder
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Folder")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for folders")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folders")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Folder = foreign
		if foreign.R == nil {
			foreign.R = &folderR{}
		}
		foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.FolderID == foreign.ID {
				local.R.Folder = foreign
				if foreign.R == nil {
					foreign.R = &folderR{}
				}
				foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, local)
				break
			}
		}
	}

	return nil
}

// LoadPermission allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderPermissionL) LoadPermission(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolderPermission any, mods queries.Applicator) error {
	var slice []*FolderPermission
	var object *FolderPermission

	if singular {
		var ok bool
		object, ok = maybeFolderPermission.(*FolderPermission)
		if !ok {
			object = new(FolderPermission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolderPermission))
			}
		}
	} else {
		s, ok := maybeFolderPermission.(*[]*FolderPermission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolderPermission))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderPermissionR{}
		}
		args[object.PermissionID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderPermissionR{}
			}

			args[obj.PermissionID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`permission_definitions`),
		qm.WhereIn(`permission_definitions.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PermissionDefinition")
	}

	var resultSlice []*PermissionDefinition
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PermissionDefinition")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for permission_definitions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for permission_definitions")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Permission = foreign
		if foreign.R == nil {
			foreign.R = &permissionDefinitionR{}
		}
		foreign.R.PermissionFolderPermissions = append(foreign.R.PermissionFolderPermissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PermissionID == foreign.ID {
				local.R.Permission = foreign
				if foreign.R == nil {
					foreign.R = &permissionDefinitionR{}
				}
				foreign.R.PermissionFolderPermissions = append(foreign.R.PermissionFolderPermissions, local)
				break
			}
		}
	}

	return nil
}

// LoadPortalRole allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderPermissionL) LoadPortalRole(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolderPermission any, mods queries.Applicator) error {
	var slice []*FolderPermission
	var object *FolderPermission

	if singular {
		var ok bool
		object, ok = maybeFolderPermission.(*FolderPermission)
		if !ok {
			object = new(FolderPermission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolderPermission))
			}
		}
	} else {
		s, ok := maybeFolderPermission.(*[]*FolderPermission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolderPermission))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderPermissionR{}
		}
		if !queries.IsNil(object.PortalRoleID) {
			args[object.PortalRoleID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderPermissionR{}
			}

			if !queries.IsNil(obj.PortalRoleID) {
				args[obj.PortalRoleID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`portal_roles`),
		qm.WhereIn(`portal_roles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PortalRole")
	}

	var resultSlice []*PortalRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PortalRole")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for portal_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for portal_roles")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.PortalRole = foreign
		if foreign.R == nil {
			foreign.R = &portalRoleR{}
		}
		foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.PortalRoleID, foreign.ID) {
				local.R.PortalRole = foreign
				if foreign.R == nil {
					foreign.R = &portalRoleR{}
				}
				foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (folderPermissionL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybeFolderPermission any, mods queries.Applicator) error {
	var slice []*FolderPermission
	var object *FolderPermission

	if singular {
		var ok bool
		object, ok = maybeFolderPermission.(*FolderPermission)
		if !ok {
			object = new(FolderPermission)
			ok = queries.SetFromEmbeddedStruct(&object, &maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybeFolderPermission))
			}
		}
	} else {
		s, ok := maybeFolderPermission.(*[]*FolderPermission)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybeFolderPermission)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybeFolderPermission))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &folderPermissionR{}
		}
		if !queries.IsNil(object.UserID) {
			args[object.UserID] = struct{}{}
		}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &folderPermissionR{}
			}

			if !queries.IsNil(obj.UserID) {
				args[obj.UserID] = struct{}{}
			}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if queries.Equal(local.UserID, foreign.ID) {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.FolderPermissions = append(foreign.R.FolderPermissions, local)
				break
			}
		}
	}

	return nil
}

// SetCreatedByUser of the folderPermission to the related item.
// Sets o.R.CreatedByUser to related.
// Adds o to related.R.CreatedByFolderPermissions.
func (o *FolderPermission) SetCreatedByUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"created_by"}),
		strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.CreatedBy = related.ID
	if o.R == nil {
		o.R = &folderPermissionR{
			CreatedByUser: related,
		}
	} else {
		o.R.CreatedByUser = related
	}

	if related.R == nil {
		related.R = &userR{
			CreatedByFolderPermissions: FolderPermissionSlice{o},
		}
	} else {
		related.R.CreatedByFolderPermissions = append(related.R.CreatedByFolderPermissions, o)
	}

	return nil
}

// SetFolder of the folderPermission to the related item.
// Sets o.R.Folder to related.
// Adds o to related.R.FolderPermissions.
func (o *FolderPermission) SetFolder(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Folder) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"folder_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.FolderID = related.ID
	if o.R == nil {
		o.R = &folderPermissionR{
			Folder: related,
		}
	} else {
		o.R.Folder = related
	}

	if related.R == nil {
		related.R = &folderR{
			FolderPermissions: FolderPermissionSlice{o},
		}
	} else {
		related.R.FolderPermissions = append(related.R.FolderPermissions, o)
	}

	return nil
}

// SetPermission of the folderPermission to the related item.
// Sets o.R.Permission to related.
// Adds o to related.R.PermissionFolderPermissions.
func (o *FolderPermission) SetPermission(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PermissionDefinition) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"permission_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PermissionID = related.ID
	if o.R == nil {
		o.R = &folderPermissionR{
			Permission: related,
		}
	} else {
		o.R.Permission = related
	}

	if related.R == nil {
		related.R = &permissionDefinitionR{
			PermissionFolderPermissions: FolderPermissionSlice{o},
		}
	} else {
		related.R.PermissionFolderPermissions = append(related.R.PermissionFolderPermissions, o)
	}

	return nil
}

// SetPortalRole of the folderPermission to the related item.
// Sets o.R.PortalRole to related.
// Adds o to related.R.FolderPermissions.
func (o *FolderPermission) SetPortalRole(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PortalRole) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"portal_role_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.PortalRoleID, related.ID)
	if o.R == nil {
		o.R = &folderPermissionR{
			PortalRole: related,
		}
	} else {
		o.R.PortalRole = related
	}

	if related.R == nil {
		related.R = &portalRoleR{
			FolderPermissions: FolderPermissionSlice{o},
		}
	} else {
		related.R.FolderPermissions = append(related.R.FolderPermissions, o)
	}

	return nil
}

// RemovePortalRole relationship.
// Sets o.R.PortalRole to nil.
// Removes o from all passed in related items' relationships struct.
func (o *FolderPermission) RemovePortalRole(ctx context.Context, exec boil.ContextExecutor, related *PortalRole) error {
	var err error

	queries.SetScanner(&o.PortalRoleID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("portal_role_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.PortalRole = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FolderPermissions {
		if queries.Equal(o.PortalRoleID, ri.PortalRoleID) {
			continue
		}

		ln := len(related.R.FolderPermissions)
		if ln > 1 && i < ln-1 {
			related.R.FolderPermissions[i] = related.R.FolderPermissions[ln-1]
		}
		related.R.FolderPermissions = related.R.FolderPermissions[:ln-1]
		break
	}
	return nil
}

// SetUser of the folderPermission to the related item.
// Sets o.R.User to related.
// Adds o to related.R.FolderPermissions.
func (o *FolderPermission) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	queries.Assign(&o.UserID, related.ID)
	if o.R == nil {
		o.R = &folderPermissionR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			FolderPermissions: FolderPermissionSlice{o},
		}
	} else {
		related.R.FolderPermissions = append(related.R.FolderPermissions, o)
	}

	return nil
}

// RemoveUser relationship.
// Sets o.R.User to nil.
// Removes o from all passed in related items' relationships struct.
func (o *FolderPermission) RemoveUser(ctx context.Context, exec boil.ContextExecutor, related *User) error {
	var err error

	queries.SetScanner(&o.UserID, nil)
	if _, err = o.Update(ctx, exec, boil.Whitelist("user_id")); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	if o.R != nil {
		o.R.User = nil
	}
	if related == nil || related.R == nil {
		return nil
	}

	for i, ri := range related.R.FolderPermissions {
		if queries.Equal(o.UserID, ri.UserID) {
			continue
		}

		ln := len(related.R.FolderPermissions)
		if ln > 1 && i < ln-1 {
			related.R.FolderPermissions[i] = related.R.FolderPermissions[ln-1]
		}
		related.R.FolderPermissions = related.R.FolderPermissions[:ln-1]
		break
	}
	return nil
}

// FolderPermissions retrieves all the records using an executor.
func FolderPermissions(mods ...qm.QueryMod) folderPermissionQuery {
	mods = append(mods, qm.From("\"folder_permissions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"folder_permissions\".*"})
	}

	return folderPermissionQuery{q}
}

// FindFolderPermission retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindFolderPermission(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*FolderPermission, error) {
	folderPermissionObj := &FolderPermission{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"folder_permissions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, folderPermissionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from folder_permissions")
	}

	return folderPermissionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *FolderPermission) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no folder_permissions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(folderPermissionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	folderPermissionInsertCacheMut.RLock()
	cache, cached := folderPermissionInsertCache[key]
	folderPermissionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			folderPermissionAllColumns,
			folderPermissionColumnsWithDefault,
			folderPermissionColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, folderPermissionGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(folderPermissionType, folderPermissionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(folderPermissionType, folderPermissionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"folder_permissions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"folder_permissions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into folder_permissions")
	}

	if !cached {
		folderPermissionInsertCacheMut.Lock()
		folderPermissionInsertCache[key] = cache
		folderPermissionInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the FolderPermission.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *FolderPermission) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	var err error
	key := makeCacheKey(columns, nil)
	folderPermissionUpdateCacheMut.RLock()
	cache, cached := folderPermissionUpdateCache[key]
	folderPermissionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			folderPermissionAllColumns,
			folderPermissionPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, folderPermissionGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update folder_permissions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"folder_permissions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, folderPermissionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(folderPermissionType, folderPermissionMapping, append(wl, folderPermissionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update folder_permissions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for folder_permissions")
	}

	if !cached {
		folderPermissionUpdateCacheMut.Lock()
		folderPermissionUpdateCache[key] = cache
		folderPermissionUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q folderPermissionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for folder_permissions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for folder_permissions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o FolderPermissionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"folder_permissions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, folderPermissionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in folderPermission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all folderPermission")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *FolderPermission) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no folder_permissions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(folderPermissionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	folderPermissionUpsertCacheMut.RLock()
	cache, cached := folderPermissionUpsertCache[key]
	folderPermissionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			folderPermissionAllColumns,
			folderPermissionColumnsWithDefault,
			folderPermissionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			folderPermissionAllColumns,
			folderPermissionPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, folderPermissionGeneratedColumns)
		update = strmangle.SetComplement(update, folderPermissionGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert folder_permissions, could not build update column list")
		}

		ret := strmangle.SetComplement(folderPermissionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(folderPermissionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert folder_permissions, could not build conflict column list")
			}

			conflict = make([]string, len(folderPermissionPrimaryKeyColumns))
			copy(conflict, folderPermissionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"folder_permissions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(folderPermissionType, folderPermissionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(folderPermissionType, folderPermissionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert folder_permissions")
	}

	if !cached {
		folderPermissionUpsertCacheMut.Lock()
		folderPermissionUpsertCache[key] = cache
		folderPermissionUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single FolderPermission record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *FolderPermission) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no FolderPermission provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), folderPermissionPrimaryKeyMapping)
	sql := "DELETE FROM \"folder_permissions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from folder_permissions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for folder_permissions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q folderPermissionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no folderPermissionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from folder_permissions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for folder_permissions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o FolderPermissionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"folder_permissions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, folderPermissionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from folderPermission slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for folder_permissions")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *FolderPermission) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindFolderPermission(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *FolderPermissionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := FolderPermissionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), folderPermissionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"folder_permissions\".* FROM \"folder_permissions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, folderPermissionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in FolderPermissionSlice")
	}

	*o = slice

	return nil
}

// FolderPermissionExists checks if the FolderPermission row exists.
func FolderPermissionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"folder_permissions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if folder_permissions exists")
	}

	return exists, nil
}

// Exists checks if the FolderPermission row exists.
func (o *FolderPermission) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return FolderPermissionExists(ctx, exec, o.ID)
}
