// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/null/v8"
	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PermissionDefinition is an object representing the database table.
type PermissionDefinition struct {
	ID          int64       `boil:"id" json:"id" toml:"id" yaml:"id"`
	Name        string      `boil:"name" json:"name" toml:"name" yaml:"name"`
	Description null.String `boil:"description" json:"description,omitempty" toml:"description" yaml:"description,omitempty"`
	CreatedAt   time.Time   `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt   time.Time   `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *permissionDefinitionR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L permissionDefinitionL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PermissionDefinitionColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "id",
	Name:        "name",
	Description: "description",
	CreatedAt:   "created_at",
	UpdatedAt:   "updated_at",
}

var PermissionDefinitionTableColumns = struct {
	ID          string
	Name        string
	Description string
	CreatedAt   string
	UpdatedAt   string
}{
	ID:          "permission_definitions.id",
	Name:        "permission_definitions.name",
	Description: "permission_definitions.description",
	CreatedAt:   "permission_definitions.created_at",
	UpdatedAt:   "permission_definitions.updated_at",
}

// Generated where

var PermissionDefinitionWhere = struct {
	ID          whereHelperint64
	Name        whereHelperstring
	Description whereHelpernull_String
	CreatedAt   whereHelpertime_Time
	UpdatedAt   whereHelpertime_Time
}{
	ID:          whereHelperint64{field: "\"permission_definitions\".\"id\""},
	Name:        whereHelperstring{field: "\"permission_definitions\".\"name\""},
	Description: whereHelpernull_String{field: "\"permission_definitions\".\"description\""},
	CreatedAt:   whereHelpertime_Time{field: "\"permission_definitions\".\"created_at\""},
	UpdatedAt:   whereHelpertime_Time{field: "\"permission_definitions\".\"updated_at\""},
}

// PermissionDefinitionRels is where relationship names are stored.
var PermissionDefinitionRels = struct {
	PermissionFolderPermissions string
}{
	PermissionFolderPermissions: "PermissionFolderPermissions",
}

// permissionDefinitionR is where relationships are stored.
type permissionDefinitionR struct {
	PermissionFolderPermissions FolderPermissionSlice `boil:"PermissionFolderPermissions" json:"PermissionFolderPermissions" toml:"PermissionFolderPermissions" yaml:"PermissionFolderPermissions"`
}

// NewStruct creates a new relationship struct
func (*permissionDefinitionR) NewStruct() *permissionDefinitionR {
	return &permissionDefinitionR{}
}

func (o *PermissionDefinition) GetPermissionFolderPermissions() FolderPermissionSlice {
	if o == nil {
		return nil
	}

	return o.R.GetPermissionFolderPermissions()
}

func (r *permissionDefinitionR) GetPermissionFolderPermissions() FolderPermissionSlice {
	if r == nil {
		return nil
	}

	return r.PermissionFolderPermissions
}

// permissionDefinitionL is where Load methods for each relationship are stored.
type permissionDefinitionL struct{}

var (
	permissionDefinitionAllColumns            = []string{"id", "name", "description", "created_at", "updated_at"}
	permissionDefinitionColumnsWithoutDefault = []string{"name"}
	permissionDefinitionColumnsWithDefault    = []string{"id", "description", "created_at", "updated_at"}
	permissionDefinitionPrimaryKeyColumns     = []string{"id"}
	permissionDefinitionGeneratedColumns      = []string{"id"}
)

type (
	// PermissionDefinitionSlice is an alias for a slice of pointers to PermissionDefinition.
	// This should almost always be used instead of []PermissionDefinition.
	PermissionDefinitionSlice []*PermissionDefinition

	permissionDefinitionQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	permissionDefinitionType                 = reflect.TypeOf(&PermissionDefinition{})
	permissionDefinitionMapping              = queries.MakeStructMapping(permissionDefinitionType)
	permissionDefinitionPrimaryKeyMapping, _ = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, permissionDefinitionPrimaryKeyColumns)
	permissionDefinitionInsertCacheMut       sync.RWMutex
	permissionDefinitionInsertCache          = make(map[string]insertCache)
	permissionDefinitionUpdateCacheMut       sync.RWMutex
	permissionDefinitionUpdateCache          = make(map[string]updateCache)
	permissionDefinitionUpsertCacheMut       sync.RWMutex
	permissionDefinitionUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single permissionDefinition record from the query.
func (q permissionDefinitionQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PermissionDefinition, error) {
	o := &PermissionDefinition{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for permission_definitions")
	}

	return o, nil
}

// All returns all PermissionDefinition records from the query.
func (q permissionDefinitionQuery) All(ctx context.Context, exec boil.ContextExecutor) (PermissionDefinitionSlice, error) {
	var o []*PermissionDefinition

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PermissionDefinition slice")
	}

	return o, nil
}

// Count returns the count of all PermissionDefinition records in the query.
func (q permissionDefinitionQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count permission_definitions rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q permissionDefinitionQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if permission_definitions exists")
	}

	return count > 0, nil
}

// PermissionFolderPermissions retrieves all the folder_permission's FolderPermissions with an executor via permission_id column.
func (o *PermissionDefinition) PermissionFolderPermissions(mods ...qm.QueryMod) folderPermissionQuery {
	var queryMods []qm.QueryMod
	if len(mods) != 0 {
		queryMods = append(queryMods, mods...)
	}

	queryMods = append(queryMods,
		qm.Where("\"folder_permissions\".\"permission_id\"=?", o.ID),
	)

	return FolderPermissions(queryMods...)
}

// LoadPermissionFolderPermissions allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for a 1-M or N-M relationship.
func (permissionDefinitionL) LoadPermissionFolderPermissions(ctx context.Context, e boil.ContextExecutor, singular bool, maybePermissionDefinition any, mods queries.Applicator) error {
	var slice []*PermissionDefinition
	var object *PermissionDefinition

	if singular {
		var ok bool
		object, ok = maybePermissionDefinition.(*PermissionDefinition)
		if !ok {
			object = new(PermissionDefinition)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePermissionDefinition)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePermissionDefinition))
			}
		}
	} else {
		s, ok := maybePermissionDefinition.(*[]*PermissionDefinition)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePermissionDefinition)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePermissionDefinition))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &permissionDefinitionR{}
		}
		args[object.ID] = struct{}{}
	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &permissionDefinitionR{}
			}
			args[obj.ID] = struct{}{}
		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`folder_permissions`),
		qm.WhereIn(`folder_permissions.permission_id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load folder_permissions")
	}

	var resultSlice []*FolderPermission
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice folder_permissions")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results in eager load on folder_permissions")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for folder_permissions")
	}

	if singular {
		object.R.PermissionFolderPermissions = resultSlice
		for _, foreign := range resultSlice {
			if foreign.R == nil {
				foreign.R = &folderPermissionR{}
			}
			foreign.R.Permission = object
		}
		return nil
	}

	for _, foreign := range resultSlice {
		for _, local := range slice {
			if local.ID == foreign.PermissionID {
				local.R.PermissionFolderPermissions = append(local.R.PermissionFolderPermissions, foreign)
				if foreign.R == nil {
					foreign.R = &folderPermissionR{}
				}
				foreign.R.Permission = local
				break
			}
		}
	}

	return nil
}

// AddPermissionFolderPermissions adds the given related objects to the existing relationships
// of the permission_definition, optionally inserting them as new records.
// Appends related to o.R.PermissionFolderPermissions.
// Sets related.R.Permission appropriately.
func (o *PermissionDefinition) AddPermissionFolderPermissions(ctx context.Context, exec boil.ContextExecutor, insert bool, related ...*FolderPermission) error {
	var err error
	for _, rel := range related {
		if insert {
			rel.PermissionID = o.ID
			if err = rel.Insert(ctx, exec, boil.Infer()); err != nil {
				return errors.Wrap(err, "failed to insert into foreign table")
			}
		} else {
			updateQuery := fmt.Sprintf(
				"UPDATE \"folder_permissions\" SET %s WHERE %s",
				strmangle.SetParamNames("\"", "\"", 1, []string{"permission_id"}),
				strmangle.WhereClause("\"", "\"", 2, folderPermissionPrimaryKeyColumns),
			)
			values := []any{o.ID, rel.ID}

			if boil.IsDebug(ctx) {
				writer := boil.DebugWriterFrom(ctx)
				fmt.Fprintln(writer, updateQuery)
				fmt.Fprintln(writer, values)
			}
			if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
				return errors.Wrap(err, "failed to update foreign table")
			}

			rel.PermissionID = o.ID
		}
	}

	if o.R == nil {
		o.R = &permissionDefinitionR{
			PermissionFolderPermissions: related,
		}
	} else {
		o.R.PermissionFolderPermissions = append(o.R.PermissionFolderPermissions, related...)
	}

	for _, rel := range related {
		if rel.R == nil {
			rel.R = &folderPermissionR{
				Permission: o,
			}
		} else {
			rel.R.Permission = o
		}
	}
	return nil
}

// PermissionDefinitions retrieves all the records using an executor.
func PermissionDefinitions(mods ...qm.QueryMod) permissionDefinitionQuery {
	mods = append(mods, qm.From("\"permission_definitions\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"permission_definitions\".*"})
	}

	return permissionDefinitionQuery{q}
}

// FindPermissionDefinition retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPermissionDefinition(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PermissionDefinition, error) {
	permissionDefinitionObj := &PermissionDefinition{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"permission_definitions\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, permissionDefinitionObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from permission_definitions")
	}

	return permissionDefinitionObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PermissionDefinition) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no permission_definitions provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(permissionDefinitionColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	permissionDefinitionInsertCacheMut.RLock()
	cache, cached := permissionDefinitionInsertCache[key]
	permissionDefinitionInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			permissionDefinitionAllColumns,
			permissionDefinitionColumnsWithDefault,
			permissionDefinitionColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, permissionDefinitionGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"permission_definitions\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"permission_definitions\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into permission_definitions")
	}

	if !cached {
		permissionDefinitionInsertCacheMut.Lock()
		permissionDefinitionInsertCache[key] = cache
		permissionDefinitionInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the PermissionDefinition.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PermissionDefinition) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	permissionDefinitionUpdateCacheMut.RLock()
	cache, cached := permissionDefinitionUpdateCache[key]
	permissionDefinitionUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			permissionDefinitionAllColumns,
			permissionDefinitionPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, permissionDefinitionGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update permission_definitions, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"permission_definitions\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, permissionDefinitionPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, append(wl, permissionDefinitionPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update permission_definitions row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for permission_definitions")
	}

	if !cached {
		permissionDefinitionUpdateCacheMut.Lock()
		permissionDefinitionUpdateCache[key] = cache
		permissionDefinitionUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q permissionDefinitionQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for permission_definitions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for permission_definitions")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PermissionDefinitionSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), permissionDefinitionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"permission_definitions\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, permissionDefinitionPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in permissionDefinition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all permissionDefinition")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PermissionDefinition) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no permission_definitions provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(permissionDefinitionColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	permissionDefinitionUpsertCacheMut.RLock()
	cache, cached := permissionDefinitionUpsertCache[key]
	permissionDefinitionUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			permissionDefinitionAllColumns,
			permissionDefinitionColumnsWithDefault,
			permissionDefinitionColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			permissionDefinitionAllColumns,
			permissionDefinitionPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, permissionDefinitionGeneratedColumns)
		update = strmangle.SetComplement(update, permissionDefinitionGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert permission_definitions, could not build update column list")
		}

		ret := strmangle.SetComplement(permissionDefinitionAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(permissionDefinitionPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert permission_definitions, could not build conflict column list")
			}

			conflict = make([]string, len(permissionDefinitionPrimaryKeyColumns))
			copy(conflict, permissionDefinitionPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"permission_definitions\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(permissionDefinitionType, permissionDefinitionMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert permission_definitions")
	}

	if !cached {
		permissionDefinitionUpsertCacheMut.Lock()
		permissionDefinitionUpsertCache[key] = cache
		permissionDefinitionUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single PermissionDefinition record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PermissionDefinition) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PermissionDefinition provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), permissionDefinitionPrimaryKeyMapping)
	sql := "DELETE FROM \"permission_definitions\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from permission_definitions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for permission_definitions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q permissionDefinitionQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no permissionDefinitionQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from permission_definitions")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for permission_definitions")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PermissionDefinitionSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), permissionDefinitionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"permission_definitions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, permissionDefinitionPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from permissionDefinition slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for permission_definitions")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PermissionDefinition) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPermissionDefinition(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PermissionDefinitionSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PermissionDefinitionSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), permissionDefinitionPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"permission_definitions\".* FROM \"permission_definitions\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, permissionDefinitionPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PermissionDefinitionSlice")
	}

	*o = slice

	return nil
}

// PermissionDefinitionExists checks if the PermissionDefinition row exists.
func PermissionDefinitionExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"permission_definitions\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if permission_definitions exists")
	}

	return exists, nil
}

// Exists checks if the PermissionDefinition row exists.
func (o *PermissionDefinition) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PermissionDefinitionExists(ctx, exec, o.ID)
}
