// Code generated by SQLBoiler 4.19.7 (https://github.com/aarondl/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"reflect"
	"strconv"
	"strings"
	"sync"
	"time"

	"github.com/aarondl/sqlboiler/v4/boil"
	"github.com/aarondl/sqlboiler/v4/queries"
	"github.com/aarondl/sqlboiler/v4/queries/qm"
	"github.com/aarondl/sqlboiler/v4/queries/qmhelper"
	"github.com/aarondl/strmangle"
	"github.com/friendsofgo/errors"
)

// PortalMembership is an object representing the database table.
type PortalMembership struct {
	ID           int64     `boil:"id" json:"id" toml:"id" yaml:"id"`
	PortalID     int64     `boil:"portal_id" json:"portal_id" toml:"portal_id" yaml:"portal_id"`
	UserID       int64     `boil:"user_id" json:"user_id" toml:"user_id" yaml:"user_id"`
	PortalRoleID int64     `boil:"portal_role_id" json:"portal_role_id" toml:"portal_role_id" yaml:"portal_role_id"`
	CreatedAt    time.Time `boil:"created_at" json:"created_at" toml:"created_at" yaml:"created_at"`
	UpdatedAt    time.Time `boil:"updated_at" json:"updated_at" toml:"updated_at" yaml:"updated_at"`

	R *portalMembershipR `boil:"-" json:"-" toml:"-" yaml:"-"`
	L portalMembershipL  `boil:"-" json:"-" toml:"-" yaml:"-"`
}

var PortalMembershipColumns = struct {
	ID           string
	PortalID     string
	UserID       string
	PortalRoleID string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "id",
	PortalID:     "portal_id",
	UserID:       "user_id",
	PortalRoleID: "portal_role_id",
	CreatedAt:    "created_at",
	UpdatedAt:    "updated_at",
}

var PortalMembershipTableColumns = struct {
	ID           string
	PortalID     string
	UserID       string
	PortalRoleID string
	CreatedAt    string
	UpdatedAt    string
}{
	ID:           "portal_memberships.id",
	PortalID:     "portal_memberships.portal_id",
	UserID:       "portal_memberships.user_id",
	PortalRoleID: "portal_memberships.portal_role_id",
	CreatedAt:    "portal_memberships.created_at",
	UpdatedAt:    "portal_memberships.updated_at",
}

// Generated where

var PortalMembershipWhere = struct {
	ID           whereHelperint64
	PortalID     whereHelperint64
	UserID       whereHelperint64
	PortalRoleID whereHelperint64
	CreatedAt    whereHelpertime_Time
	UpdatedAt    whereHelpertime_Time
}{
	ID:           whereHelperint64{field: "\"portal_memberships\".\"id\""},
	PortalID:     whereHelperint64{field: "\"portal_memberships\".\"portal_id\""},
	UserID:       whereHelperint64{field: "\"portal_memberships\".\"user_id\""},
	PortalRoleID: whereHelperint64{field: "\"portal_memberships\".\"portal_role_id\""},
	CreatedAt:    whereHelpertime_Time{field: "\"portal_memberships\".\"created_at\""},
	UpdatedAt:    whereHelpertime_Time{field: "\"portal_memberships\".\"updated_at\""},
}

// PortalMembershipRels is where relationship names are stored.
var PortalMembershipRels = struct {
	Portal     string
	PortalRole string
	User       string
}{
	Portal:     "Portal",
	PortalRole: "PortalRole",
	User:       "User",
}

// portalMembershipR is where relationships are stored.
type portalMembershipR struct {
	Portal     *Portal     `boil:"Portal" json:"Portal" toml:"Portal" yaml:"Portal"`
	PortalRole *PortalRole `boil:"PortalRole" json:"PortalRole" toml:"PortalRole" yaml:"PortalRole"`
	User       *User       `boil:"User" json:"User" toml:"User" yaml:"User"`
}

// NewStruct creates a new relationship struct
func (*portalMembershipR) NewStruct() *portalMembershipR {
	return &portalMembershipR{}
}

func (o *PortalMembership) GetPortal() *Portal {
	if o == nil {
		return nil
	}

	return o.R.GetPortal()
}

func (r *portalMembershipR) GetPortal() *Portal {
	if r == nil {
		return nil
	}

	return r.Portal
}

func (o *PortalMembership) GetPortalRole() *PortalRole {
	if o == nil {
		return nil
	}

	return o.R.GetPortalRole()
}

func (r *portalMembershipR) GetPortalRole() *PortalRole {
	if r == nil {
		return nil
	}

	return r.PortalRole
}

func (o *PortalMembership) GetUser() *User {
	if o == nil {
		return nil
	}

	return o.R.GetUser()
}

func (r *portalMembershipR) GetUser() *User {
	if r == nil {
		return nil
	}

	return r.User
}

// portalMembershipL is where Load methods for each relationship are stored.
type portalMembershipL struct{}

var (
	portalMembershipAllColumns            = []string{"id", "portal_id", "user_id", "portal_role_id", "created_at", "updated_at"}
	portalMembershipColumnsWithoutDefault = []string{"portal_id", "user_id", "portal_role_id"}
	portalMembershipColumnsWithDefault    = []string{"id", "created_at", "updated_at"}
	portalMembershipPrimaryKeyColumns     = []string{"id"}
	portalMembershipGeneratedColumns      = []string{"id"}
)

type (
	// PortalMembershipSlice is an alias for a slice of pointers to PortalMembership.
	// This should almost always be used instead of []PortalMembership.
	PortalMembershipSlice []*PortalMembership

	portalMembershipQuery struct {
		*queries.Query
	}
)

// Cache for insert, update and upsert
var (
	portalMembershipType                 = reflect.TypeOf(&PortalMembership{})
	portalMembershipMapping              = queries.MakeStructMapping(portalMembershipType)
	portalMembershipPrimaryKeyMapping, _ = queries.BindMapping(portalMembershipType, portalMembershipMapping, portalMembershipPrimaryKeyColumns)
	portalMembershipInsertCacheMut       sync.RWMutex
	portalMembershipInsertCache          = make(map[string]insertCache)
	portalMembershipUpdateCacheMut       sync.RWMutex
	portalMembershipUpdateCache          = make(map[string]updateCache)
	portalMembershipUpsertCacheMut       sync.RWMutex
	portalMembershipUpsertCache          = make(map[string]insertCache)
)

var (
	// Force time package dependency for automated UpdatedAt/CreatedAt.
	_ = time.Second
	// Force qmhelper dependency for where clause generation (which doesn't
	// always happen)
	_ = qmhelper.Where
)

// One returns a single portalMembership record from the query.
func (q portalMembershipQuery) One(ctx context.Context, exec boil.ContextExecutor) (*PortalMembership, error) {
	o := &PortalMembership{}

	queries.SetLimit(q.Query, 1)

	err := q.Bind(ctx, exec, o)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: failed to execute a one query for portal_memberships")
	}

	return o, nil
}

// All returns all PortalMembership records from the query.
func (q portalMembershipQuery) All(ctx context.Context, exec boil.ContextExecutor) (PortalMembershipSlice, error) {
	var o []*PortalMembership

	err := q.Bind(ctx, exec, &o)
	if err != nil {
		return nil, errors.Wrap(err, "models: failed to assign all query results to PortalMembership slice")
	}

	return o, nil
}

// Count returns the count of all PortalMembership records in the query.
func (q portalMembershipQuery) Count(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to count portal_memberships rows")
	}

	return count, nil
}

// Exists checks if the row exists in the table.
func (q portalMembershipQuery) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	var count int64

	queries.SetSelect(q.Query, nil)
	queries.SetCount(q.Query)
	queries.SetLimit(q.Query, 1)

	err := q.Query.QueryRowContext(ctx, exec).Scan(&count)
	if err != nil {
		return false, errors.Wrap(err, "models: failed to check if portal_memberships exists")
	}

	return count > 0, nil
}

// Portal pointed to by the foreign key.
func (o *PortalMembership) Portal(mods ...qm.QueryMod) portalQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PortalID),
	}

	queryMods = append(queryMods, mods...)

	return Portals(queryMods...)
}

// PortalRole pointed to by the foreign key.
func (o *PortalMembership) PortalRole(mods ...qm.QueryMod) portalRoleQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.PortalRoleID),
	}

	queryMods = append(queryMods, mods...)

	return PortalRoles(queryMods...)
}

// User pointed to by the foreign key.
func (o *PortalMembership) User(mods ...qm.QueryMod) userQuery {
	queryMods := []qm.QueryMod{
		qm.Where("\"id\" = ?", o.UserID),
	}

	queryMods = append(queryMods, mods...)

	return Users(queryMods...)
}

// LoadPortal allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (portalMembershipL) LoadPortal(ctx context.Context, e boil.ContextExecutor, singular bool, maybePortalMembership any, mods queries.Applicator) error {
	var slice []*PortalMembership
	var object *PortalMembership

	if singular {
		var ok bool
		object, ok = maybePortalMembership.(*PortalMembership)
		if !ok {
			object = new(PortalMembership)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePortalMembership))
			}
		}
	} else {
		s, ok := maybePortalMembership.(*[]*PortalMembership)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePortalMembership))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &portalMembershipR{}
		}
		args[object.PortalID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &portalMembershipR{}
			}

			args[obj.PortalID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`portals`),
		qm.WhereIn(`portals.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load Portal")
	}

	var resultSlice []*Portal
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice Portal")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for portals")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for portals")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.Portal = foreign
		if foreign.R == nil {
			foreign.R = &portalR{}
		}
		foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PortalID == foreign.ID {
				local.R.Portal = foreign
				if foreign.R == nil {
					foreign.R = &portalR{}
				}
				foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, local)
				break
			}
		}
	}

	return nil
}

// LoadPortalRole allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (portalMembershipL) LoadPortalRole(ctx context.Context, e boil.ContextExecutor, singular bool, maybePortalMembership any, mods queries.Applicator) error {
	var slice []*PortalMembership
	var object *PortalMembership

	if singular {
		var ok bool
		object, ok = maybePortalMembership.(*PortalMembership)
		if !ok {
			object = new(PortalMembership)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePortalMembership))
			}
		}
	} else {
		s, ok := maybePortalMembership.(*[]*PortalMembership)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePortalMembership))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &portalMembershipR{}
		}
		args[object.PortalRoleID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &portalMembershipR{}
			}

			args[obj.PortalRoleID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`portal_roles`),
		qm.WhereIn(`portal_roles.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load PortalRole")
	}

	var resultSlice []*PortalRole
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice PortalRole")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for portal_roles")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for portal_roles")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.PortalRole = foreign
		if foreign.R == nil {
			foreign.R = &portalRoleR{}
		}
		foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.PortalRoleID == foreign.ID {
				local.R.PortalRole = foreign
				if foreign.R == nil {
					foreign.R = &portalRoleR{}
				}
				foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, local)
				break
			}
		}
	}

	return nil
}

// LoadUser allows an eager lookup of values, cached into the
// loaded structs of the objects. This is for an N-1 relationship.
func (portalMembershipL) LoadUser(ctx context.Context, e boil.ContextExecutor, singular bool, maybePortalMembership any, mods queries.Applicator) error {
	var slice []*PortalMembership
	var object *PortalMembership

	if singular {
		var ok bool
		object, ok = maybePortalMembership.(*PortalMembership)
		if !ok {
			object = new(PortalMembership)
			ok = queries.SetFromEmbeddedStruct(&object, &maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", object, maybePortalMembership))
			}
		}
	} else {
		s, ok := maybePortalMembership.(*[]*PortalMembership)
		if ok {
			slice = *s
		} else {
			ok = queries.SetFromEmbeddedStruct(&slice, maybePortalMembership)
			if !ok {
				return errors.New(fmt.Sprintf("failed to set %T from embedded struct %T", slice, maybePortalMembership))
			}
		}
	}

	args := make(map[any]struct{})
	if singular {
		if object.R == nil {
			object.R = &portalMembershipR{}
		}
		args[object.UserID] = struct{}{}

	} else {
		for _, obj := range slice {
			if obj.R == nil {
				obj.R = &portalMembershipR{}
			}

			args[obj.UserID] = struct{}{}

		}
	}

	if len(args) == 0 {
		return nil
	}

	argsSlice := make([]any, len(args))
	i := 0
	for arg := range args {
		argsSlice[i] = arg
		i++
	}

	query := NewQuery(
		qm.From(`users`),
		qm.WhereIn(`users.id in ?`, argsSlice...),
	)
	if mods != nil {
		mods.Apply(query)
	}

	results, err := query.QueryContext(ctx, e)
	if err != nil {
		return errors.Wrap(err, "failed to eager load User")
	}

	var resultSlice []*User
	if err = queries.Bind(results, &resultSlice); err != nil {
		return errors.Wrap(err, "failed to bind eager loaded slice User")
	}

	if err = results.Close(); err != nil {
		return errors.Wrap(err, "failed to close results of eager load for users")
	}
	if err = results.Err(); err != nil {
		return errors.Wrap(err, "error occurred during iteration of eager loaded relations for users")
	}

	if len(resultSlice) == 0 {
		return nil
	}

	if singular {
		foreign := resultSlice[0]
		object.R.User = foreign
		if foreign.R == nil {
			foreign.R = &userR{}
		}
		foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, object)
		return nil
	}

	for _, local := range slice {
		for _, foreign := range resultSlice {
			if local.UserID == foreign.ID {
				local.R.User = foreign
				if foreign.R == nil {
					foreign.R = &userR{}
				}
				foreign.R.PortalMemberships = append(foreign.R.PortalMemberships, local)
				break
			}
		}
	}

	return nil
}

// SetPortal of the portalMembership to the related item.
// Sets o.R.Portal to related.
// Adds o to related.R.PortalMemberships.
func (o *PortalMembership) SetPortal(ctx context.Context, exec boil.ContextExecutor, insert bool, related *Portal) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"portal_memberships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"portal_id"}),
		strmangle.WhereClause("\"", "\"", 2, portalMembershipPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PortalID = related.ID
	if o.R == nil {
		o.R = &portalMembershipR{
			Portal: related,
		}
	} else {
		o.R.Portal = related
	}

	if related.R == nil {
		related.R = &portalR{
			PortalMemberships: PortalMembershipSlice{o},
		}
	} else {
		related.R.PortalMemberships = append(related.R.PortalMemberships, o)
	}

	return nil
}

// SetPortalRole of the portalMembership to the related item.
// Sets o.R.PortalRole to related.
// Adds o to related.R.PortalMemberships.
func (o *PortalMembership) SetPortalRole(ctx context.Context, exec boil.ContextExecutor, insert bool, related *PortalRole) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"portal_memberships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"portal_role_id"}),
		strmangle.WhereClause("\"", "\"", 2, portalMembershipPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.PortalRoleID = related.ID
	if o.R == nil {
		o.R = &portalMembershipR{
			PortalRole: related,
		}
	} else {
		o.R.PortalRole = related
	}

	if related.R == nil {
		related.R = &portalRoleR{
			PortalMemberships: PortalMembershipSlice{o},
		}
	} else {
		related.R.PortalMemberships = append(related.R.PortalMemberships, o)
	}

	return nil
}

// SetUser of the portalMembership to the related item.
// Sets o.R.User to related.
// Adds o to related.R.PortalMemberships.
func (o *PortalMembership) SetUser(ctx context.Context, exec boil.ContextExecutor, insert bool, related *User) error {
	var err error
	if insert {
		if err = related.Insert(ctx, exec, boil.Infer()); err != nil {
			return errors.Wrap(err, "failed to insert into foreign table")
		}
	}

	updateQuery := fmt.Sprintf(
		"UPDATE \"portal_memberships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, []string{"user_id"}),
		strmangle.WhereClause("\"", "\"", 2, portalMembershipPrimaryKeyColumns),
	)
	values := []any{related.ID, o.ID}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, updateQuery)
		fmt.Fprintln(writer, values)
	}
	if _, err = exec.ExecContext(ctx, updateQuery, values...); err != nil {
		return errors.Wrap(err, "failed to update local table")
	}

	o.UserID = related.ID
	if o.R == nil {
		o.R = &portalMembershipR{
			User: related,
		}
	} else {
		o.R.User = related
	}

	if related.R == nil {
		related.R = &userR{
			PortalMemberships: PortalMembershipSlice{o},
		}
	} else {
		related.R.PortalMemberships = append(related.R.PortalMemberships, o)
	}

	return nil
}

// PortalMemberships retrieves all the records using an executor.
func PortalMemberships(mods ...qm.QueryMod) portalMembershipQuery {
	mods = append(mods, qm.From("\"portal_memberships\""))
	q := NewQuery(mods...)
	if len(queries.GetSelect(q)) == 0 {
		queries.SetSelect(q, []string{"\"portal_memberships\".*"})
	}

	return portalMembershipQuery{q}
}

// FindPortalMembership retrieves a single record by ID with an executor.
// If selectCols is empty Find will return all columns.
func FindPortalMembership(ctx context.Context, exec boil.ContextExecutor, iD int64, selectCols ...string) (*PortalMembership, error) {
	portalMembershipObj := &PortalMembership{}

	sel := "*"
	if len(selectCols) > 0 {
		sel = strings.Join(strmangle.IdentQuoteSlice(dialect.LQ, dialect.RQ, selectCols), ",")
	}
	query := fmt.Sprintf(
		"select %s from \"portal_memberships\" where \"id\"=$1", sel,
	)

	q := queries.Raw(query, iD)

	err := q.Bind(ctx, exec, portalMembershipObj)
	if err != nil {
		if errors.Is(err, sql.ErrNoRows) {
			return nil, sql.ErrNoRows
		}
		return nil, errors.Wrap(err, "models: unable to select from portal_memberships")
	}

	return portalMembershipObj, nil
}

// Insert a single record using an executor.
// See boil.Columns.InsertColumnSet documentation to understand column list inference for inserts.
func (o *PortalMembership) Insert(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) error {
	if o == nil {
		return errors.New("models: no portal_memberships provided for insertion")
	}

	var err error
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		if o.UpdatedAt.IsZero() {
			o.UpdatedAt = currTime
		}
	}

	nzDefaults := queries.NonZeroDefaultSet(portalMembershipColumnsWithDefault, o)

	key := makeCacheKey(columns, nzDefaults)
	portalMembershipInsertCacheMut.RLock()
	cache, cached := portalMembershipInsertCache[key]
	portalMembershipInsertCacheMut.RUnlock()

	if !cached {
		wl, returnColumns := columns.InsertColumnSet(
			portalMembershipAllColumns,
			portalMembershipColumnsWithDefault,
			portalMembershipColumnsWithoutDefault,
			nzDefaults,
		)
		wl = strmangle.SetComplement(wl, portalMembershipGeneratedColumns)

		cache.valueMapping, err = queries.BindMapping(portalMembershipType, portalMembershipMapping, wl)
		if err != nil {
			return err
		}
		cache.retMapping, err = queries.BindMapping(portalMembershipType, portalMembershipMapping, returnColumns)
		if err != nil {
			return err
		}
		if len(wl) != 0 {
			cache.query = fmt.Sprintf("INSERT INTO \"portal_memberships\" (\"%s\") %%sVALUES (%s)%%s", strings.Join(wl, "\",\""), strmangle.Placeholders(dialect.UseIndexPlaceholders, len(wl), 1, 1))
		} else {
			cache.query = "INSERT INTO \"portal_memberships\" %sDEFAULT VALUES%s"
		}

		var queryOutput, queryReturning string

		if len(cache.retMapping) != 0 {
			queryReturning = fmt.Sprintf(" RETURNING \"%s\"", strings.Join(returnColumns, "\",\""))
		}

		cache.query = fmt.Sprintf(cache.query, queryOutput, queryReturning)
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}

	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(queries.PtrsFromMapping(value, cache.retMapping)...)
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}

	if err != nil {
		return errors.Wrap(err, "models: unable to insert into portal_memberships")
	}

	if !cached {
		portalMembershipInsertCacheMut.Lock()
		portalMembershipInsertCache[key] = cache
		portalMembershipInsertCacheMut.Unlock()
	}

	return nil
}

// Update uses an executor to update the PortalMembership.
// See boil.Columns.UpdateColumnSet documentation to understand column list inference for updates.
// Update does not automatically update the record in case of default values. Use .Reload() to refresh the records.
func (o *PortalMembership) Update(ctx context.Context, exec boil.ContextExecutor, columns boil.Columns) (int64, error) {
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		o.UpdatedAt = currTime
	}

	var err error
	key := makeCacheKey(columns, nil)
	portalMembershipUpdateCacheMut.RLock()
	cache, cached := portalMembershipUpdateCache[key]
	portalMembershipUpdateCacheMut.RUnlock()

	if !cached {
		wl := columns.UpdateColumnSet(
			portalMembershipAllColumns,
			portalMembershipPrimaryKeyColumns,
		)
		wl = strmangle.SetComplement(wl, portalMembershipGeneratedColumns)

		if !columns.IsWhitelist() {
			wl = strmangle.SetComplement(wl, []string{"created_at"})
		}
		if len(wl) == 0 {
			return 0, errors.New("models: unable to update portal_memberships, could not build whitelist")
		}

		cache.query = fmt.Sprintf("UPDATE \"portal_memberships\" SET %s WHERE %s",
			strmangle.SetParamNames("\"", "\"", 1, wl),
			strmangle.WhereClause("\"", "\"", len(wl)+1, portalMembershipPrimaryKeyColumns),
		)
		cache.valueMapping, err = queries.BindMapping(portalMembershipType, portalMembershipMapping, append(wl, portalMembershipPrimaryKeyColumns...))
		if err != nil {
			return 0, err
		}
	}

	values := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), cache.valueMapping)

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, values)
	}
	var result sql.Result
	result, err = exec.ExecContext(ctx, cache.query, values...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update portal_memberships row")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by update for portal_memberships")
	}

	if !cached {
		portalMembershipUpdateCacheMut.Lock()
		portalMembershipUpdateCache[key] = cache
		portalMembershipUpdateCacheMut.Unlock()
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values.
func (q portalMembershipQuery) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	queries.SetUpdate(q.Query, cols)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all for portal_memberships")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected for portal_memberships")
	}

	return rowsAff, nil
}

// UpdateAll updates all rows with the specified column values, using an executor.
func (o PortalMembershipSlice) UpdateAll(ctx context.Context, exec boil.ContextExecutor, cols M) (int64, error) {
	ln := int64(len(o))
	if ln == 0 {
		return 0, nil
	}

	if len(cols) == 0 {
		return 0, errors.New("models: update all requires at least one column argument")
	}

	colNames := make([]string, len(cols))
	args := make([]any, len(cols))

	i := 0
	for name, value := range cols {
		colNames[i] = name
		args[i] = value
		i++
	}

	// Append all of the primary key values for each column
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portalMembershipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := fmt.Sprintf("UPDATE \"portal_memberships\" SET %s WHERE %s",
		strmangle.SetParamNames("\"", "\"", 1, colNames),
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), len(colNames)+1, portalMembershipPrimaryKeyColumns, len(o)))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to update all in portalMembership slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to retrieve rows affected all in update all portalMembership")
	}
	return rowsAff, nil
}

// Upsert attempts an insert using an executor, and does an update or ignore on conflict.
// See boil.Columns documentation for how to properly use updateColumns and insertColumns.
func (o *PortalMembership) Upsert(ctx context.Context, exec boil.ContextExecutor, updateOnConflict bool, conflictColumns []string, updateColumns, insertColumns boil.Columns, opts ...UpsertOptionFunc) error {
	if o == nil {
		return errors.New("models: no portal_memberships provided for upsert")
	}
	if !boil.TimestampsAreSkipped(ctx) {
		currTime := time.Now().In(boil.GetLocation())

		if o.CreatedAt.IsZero() {
			o.CreatedAt = currTime
		}
		o.UpdatedAt = currTime
	}

	nzDefaults := queries.NonZeroDefaultSet(portalMembershipColumnsWithDefault, o)

	// Build cache key in-line uglily - mysql vs psql problems
	buf := strmangle.GetBuffer()
	if updateOnConflict {
		buf.WriteByte('t')
	} else {
		buf.WriteByte('f')
	}
	buf.WriteByte('.')
	for _, c := range conflictColumns {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(updateColumns.Kind))
	for _, c := range updateColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	buf.WriteString(strconv.Itoa(insertColumns.Kind))
	for _, c := range insertColumns.Cols {
		buf.WriteString(c)
	}
	buf.WriteByte('.')
	for _, c := range nzDefaults {
		buf.WriteString(c)
	}
	key := buf.String()
	strmangle.PutBuffer(buf)

	portalMembershipUpsertCacheMut.RLock()
	cache, cached := portalMembershipUpsertCache[key]
	portalMembershipUpsertCacheMut.RUnlock()

	var err error

	if !cached {
		insert, _ := insertColumns.InsertColumnSet(
			portalMembershipAllColumns,
			portalMembershipColumnsWithDefault,
			portalMembershipColumnsWithoutDefault,
			nzDefaults,
		)

		update := updateColumns.UpdateColumnSet(
			portalMembershipAllColumns,
			portalMembershipPrimaryKeyColumns,
		)

		insert = strmangle.SetComplement(insert, portalMembershipGeneratedColumns)
		update = strmangle.SetComplement(update, portalMembershipGeneratedColumns)

		if updateOnConflict && len(update) == 0 {
			return errors.New("models: unable to upsert portal_memberships, could not build update column list")
		}

		ret := strmangle.SetComplement(portalMembershipAllColumns, strmangle.SetIntersect(insert, update))

		conflict := conflictColumns
		if len(conflict) == 0 && updateOnConflict && len(update) != 0 {
			if len(portalMembershipPrimaryKeyColumns) == 0 {
				return errors.New("models: unable to upsert portal_memberships, could not build conflict column list")
			}

			conflict = make([]string, len(portalMembershipPrimaryKeyColumns))
			copy(conflict, portalMembershipPrimaryKeyColumns)
		}
		cache.query = buildUpsertQueryPostgres(dialect, "\"portal_memberships\"", updateOnConflict, ret, update, conflict, insert, opts...)

		cache.valueMapping, err = queries.BindMapping(portalMembershipType, portalMembershipMapping, insert)
		if err != nil {
			return err
		}
		if len(ret) != 0 {
			cache.retMapping, err = queries.BindMapping(portalMembershipType, portalMembershipMapping, ret)
			if err != nil {
				return err
			}
		}
	}

	value := reflect.Indirect(reflect.ValueOf(o))
	vals := queries.ValuesFromMapping(value, cache.valueMapping)
	var returns []any
	if len(cache.retMapping) != 0 {
		returns = queries.PtrsFromMapping(value, cache.retMapping)
	}

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, cache.query)
		fmt.Fprintln(writer, vals)
	}
	if len(cache.retMapping) != 0 {
		err = exec.QueryRowContext(ctx, cache.query, vals...).Scan(returns...)
		if errors.Is(err, sql.ErrNoRows) {
			err = nil // Postgres doesn't return anything when there's no update
		}
	} else {
		_, err = exec.ExecContext(ctx, cache.query, vals...)
	}
	if err != nil {
		return errors.Wrap(err, "models: unable to upsert portal_memberships")
	}

	if !cached {
		portalMembershipUpsertCacheMut.Lock()
		portalMembershipUpsertCache[key] = cache
		portalMembershipUpsertCacheMut.Unlock()
	}

	return nil
}

// Delete deletes a single PortalMembership record with an executor.
// Delete will match against the primary key column to find the record to delete.
func (o *PortalMembership) Delete(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if o == nil {
		return 0, errors.New("models: no PortalMembership provided for delete")
	}

	args := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(o)), portalMembershipPrimaryKeyMapping)
	sql := "DELETE FROM \"portal_memberships\" WHERE \"id\"=$1"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args...)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete from portal_memberships")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by delete for portal_memberships")
	}

	return rowsAff, nil
}

// DeleteAll deletes all matching rows.
func (q portalMembershipQuery) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if q.Query == nil {
		return 0, errors.New("models: no portalMembershipQuery provided for delete all")
	}

	queries.SetDelete(q.Query)

	result, err := q.Query.ExecContext(ctx, exec)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from portal_memberships")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for portal_memberships")
	}

	return rowsAff, nil
}

// DeleteAll deletes all rows in the slice, using an executor.
func (o PortalMembershipSlice) DeleteAll(ctx context.Context, exec boil.ContextExecutor) (int64, error) {
	if len(o) == 0 {
		return 0, nil
	}

	var args []any
	for _, obj := range o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portalMembershipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "DELETE FROM \"portal_memberships\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, portalMembershipPrimaryKeyColumns, len(o))

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, args)
	}
	result, err := exec.ExecContext(ctx, sql, args...)
	if err != nil {
		return 0, errors.Wrap(err, "models: unable to delete all from portalMembership slice")
	}

	rowsAff, err := result.RowsAffected()
	if err != nil {
		return 0, errors.Wrap(err, "models: failed to get rows affected by deleteall for portal_memberships")
	}

	return rowsAff, nil
}

// Reload refetches the object from the database
// using the primary keys with an executor.
func (o *PortalMembership) Reload(ctx context.Context, exec boil.ContextExecutor) error {
	ret, err := FindPortalMembership(ctx, exec, o.ID)
	if err != nil {
		return err
	}

	*o = *ret
	return nil
}

// ReloadAll refetches every row with matching primary key column values
// and overwrites the original object slice with the newly updated slice.
func (o *PortalMembershipSlice) ReloadAll(ctx context.Context, exec boil.ContextExecutor) error {
	if o == nil || len(*o) == 0 {
		return nil
	}

	slice := PortalMembershipSlice{}
	var args []any
	for _, obj := range *o {
		pkeyArgs := queries.ValuesFromMapping(reflect.Indirect(reflect.ValueOf(obj)), portalMembershipPrimaryKeyMapping)
		args = append(args, pkeyArgs...)
	}

	sql := "SELECT \"portal_memberships\".* FROM \"portal_memberships\" WHERE " +
		strmangle.WhereClauseRepeated(string(dialect.LQ), string(dialect.RQ), 1, portalMembershipPrimaryKeyColumns, len(*o))

	q := queries.Raw(sql, args...)

	err := q.Bind(ctx, exec, &slice)
	if err != nil {
		return errors.Wrap(err, "models: unable to reload all in PortalMembershipSlice")
	}

	*o = slice

	return nil
}

// PortalMembershipExists checks if the PortalMembership row exists.
func PortalMembershipExists(ctx context.Context, exec boil.ContextExecutor, iD int64) (bool, error) {
	var exists bool
	sql := "select exists(select 1 from \"portal_memberships\" where \"id\"=$1 limit 1)"

	if boil.IsDebug(ctx) {
		writer := boil.DebugWriterFrom(ctx)
		fmt.Fprintln(writer, sql)
		fmt.Fprintln(writer, iD)
	}
	row := exec.QueryRowContext(ctx, sql, iD)

	err := row.Scan(&exists)
	if err != nil {
		return false, errors.Wrap(err, "models: unable to check if portal_memberships exists")
	}

	return exists, nil
}

// Exists checks if the PortalMembership row exists.
func (o *PortalMembership) Exists(ctx context.Context, exec boil.ContextExecutor) (bool, error) {
	return PortalMembershipExists(ctx, exec, o.ID)
}
